#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
WAF Detector Pro v1.4 - Identificação de Web Application Firewall
Estilo WAFW00F com interface gráfica + User-Agents customizados + opção de cript
Rotação automática de User-Agents do .txt (um por alvo, em ciclo)
Exportação de resultados em TXT e HTML
Uso educacional / testes autorizados somente.
"""

import tkinter as tk
from tkinter import ttk, messagebox, filedialog, scrolledtext
import threading
import queue
import socket
import ssl
import urllib.request
import urllib.error
import random
from datetime import datetime
from urllib.parse import urlparse

# ===================== USER-AGENT "CRIPTADO" (embutido no script) =====================
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
TIMEOUT = 10

# ===================== FINGERPRINTS DE WAF =====================
WAF_FINGERPRINTS = [
    {"name": "Cloudflare", "headers": {"server": "cloudflare", "cf-ray": ""}, "body": ["attention required! | cloudflare", "cloudflare ray id", "cf-error-details"], "status": [403, 503]},
    {"name": "AWS WAF (Amazon)", "headers": {"x-amzn-requestid": "", "x-amz-cf-id": ""}, "body": ["request denied", "forbidden request"], "status": [403]},
    {"name": "Akamai", "headers": {"x-akamai-transformed": "", "server": "akamai"}, "body": ["access denied", "akamai reference number", "support id"], "status": [403]},
    {"name": "Imperva (Incapsula)", "headers": {"x-iinfo": "", "x-cdn": "incapsula"}, "body": ["incapsula incident id", "request unsuccessful"], "status": [403]},
    {"name": "Sucuri", "headers": {"x-sucuri-id": "", "x-sucuri-cache": ""}, "body": ["sucuri website firewall", "cloudproxy"], "status": [403]},
    {"name": "F5 BIG-IP ASM", "headers": {"x-cnection": "", "server": "bigip"}, "body": ["the requested url was rejected", "support_id", "f5"], "status": [403]},
    {"name": "ModSecurity", "headers": {}, "body": ["mod_security", "modsecurity", "this error was generated by mod_security"], "status": [403, 406, 501]},
    {"name": "OWASP ModSecurity CRS", "headers": {}, "body": ["not accepted by the firewall"], "status": [403]},
    {"name": "Barracuda", "headers": {"server": "barracuda"}, "body": ["barracuda networks", "you have been blocked"], "status": [403]},
    {"name": "Citrix NetScaler", "headers": {"via": "ns-cache"}, "body": ["citrix", "netscaler", "ns session id"], "status": [403]},
    {"name": "DenyAll", "headers": {}, "body": ["denyall"], "status": [403]},
    {"name": "FortiWeb (Fortinet)", "headers": {}, "body": ["fortiguard", "fortiweb"], "status": [403]},
    {"name": "Sophos UTM", "headers": {"server": "sophos"}, "body": ["sophos"], "status": [403]},
    {"name": "Nginx (ModSecurity/UAIG)", "headers": {"server": "nginx"}, "body": ["nginx", "403 forbidden"], "status": [403]},
    {"name": "Envoy / Istio", "headers": {"server": "envoy", "x-envoy-upstream-service-time": ""}, "body": [], "status": []},
    {"name": "Wallarm", "headers": {"server": "wallarm"}, "body": ["wallarm"], "status": [403]},
    {"name": "Squid (proxy)", "headers": {"server": "squid"}, "body": ["squid proxy"], "status": [403]},
    {"name": "eEye SecureIIS", "headers": {}, "body": ["eeye"], "status": [403]},
    {"name": "Aspera CDN", "headers": {"server": "aspera"}, "body": [], "status": []},
    {"name": "W3AF", "headers": {}, "body": ["w3af"], "status": []},
]

MALICIOUS_BODY = "union select * from information_schema.tables--"

# ===================== FUNÇÕES BÁSICAS =====================
def fetch(url, method="GET", data=None, headers=None, user_agent=USER_AGENT):
    hdrs = {"User-Agent": user_agent, "Accept": "*/*", "Connection": "close"}
    if headers:
        hdrs.update(headers)
    req = urllib.request.Request(url, data=data, method=method, headers=hdrs)
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    try:
        resp = urllib.request.urlopen(req, timeout=TIMEOUT, context=ctx)
        body = resp.read(50000).decode("utf-8", "ignore")
        return resp.status, dict(resp.headers), body
    except urllib.error.HTTPError as e:
        body = e.read(50000).decode("utf-8", "ignore") if e.fp else ""
        return e.code, dict(e.headers or {}), body
    except Exception as e:
        return None, {}, f"ERROR:{e}"

def normalize_headers(h):
    return {k.lower(): str(v).lower() for k, v in h.items()}

def match_fingerprint(status, headers, body):
    hl = normalize_headers(headers)
    bl = body.lower()
    best = (None, 0)
    for fp in WAF_FINGERPRINTS:
        score = 0
        for hk, hv in fp["headers"].items():
            if hk in hl and (not hv or hv in hl[hk]):
                score += 2
        for sig in fp["body"]:
            if sig in bl:
                score += 3
        if fp["status"] and status in fp["status"]:
            score += 1
        if score > best[1]:
            best = (fp["name"], score)
    return best

def detect_generic_block(status, body):
    generic = ["blocked", "forbidden", "denied", "firewall", "security", "protection", "waf", "malicious", "attack detected", "violation"]
    if status in (403, 406, 429, 501):
        bl = body.lower()
        hits = [g for g in generic if g in bl]
        if hits:
            return hits
    return None

def resolve_host(host):
    try:
        return socket.gethostbyname(host)
    except Exception:
        return None

# ===================== PIPELINE =====================
def scan_target(url, log, stop_flag, user_agent=USER_AGENT, ua_label=""):
    buffer = []
    def dual_log(msg):
        buffer.append(msg)
        log(msg)

    result = {"url": url, "waf": "Nenhum detectado", "details": [], "log": [],
              "user_agent": user_agent, "ua_label": ua_label}
    if not url.startswith("http"):
        url = "http://" + url
    p = urlparse(url)
    host, scheme = p.hostname, p.scheme or "http"
    port = p.port or (443 if scheme == "https" else 80)

    dual_log(f"[*] Alvo: {url}")
    dual_log(f"[*] Porta: {port}")
    # Mostra o User-Agent COMPLETO nos resultados
    dual_log(f"[*] User-Agent utilizado: {user_agent}")
    if ua_label:
        dual_log(f"[*] Origem do User-Agent: {ua_label}")
    ip = resolve_host(host)
    dual_log(f"[*] DNS resolvido: {host} -> {ip or 'FALHA'}")
    if not ip:
        result["details"].append("Falha na resolução DNS")
        result["log"] = buffer
        return result

    # Baseline
    try:
        status, headers, body = fetch(url, user_agent=user_agent)
    except Exception as e:
        dual_log(f"[!] Erro na requisição: {e}")
        result["details"].append(f"Erro de conexão: {e}")
        result["log"] = buffer
        return result
    dual_log(f"[*] Baseline: HTTP {status} | Server: {headers.get('Server', 'n/a')}")
    result["details"].append(f"Baseline: HTTP {status}, Server={headers.get('Server','-')}")
    result["details"].append(f"User-Agent: {user_agent}")
    base_headers, base_body = normalize_headers(headers), body.lower()

    waf, score = match_fingerprint(status, headers, body)
    if waf and score >= 3:
        dual_log(f"[+] WAF detectado no baseline: {waf} (score {score})")
        result["waf"] = waf
        result["details"].append(f"Identificado no baseline (score {score})")
        result["log"] = buffer
        return result

    # Malicious tests
    tests = [
        (url + "/?q=<script>alert(1)</script>", None, "XSS via query string"),
        (url + "/?id=1%20OR%201=1", None, "SQLi via query string"),
        (url + "/?file=../../etc/passwd", None, "LFI/path traversal"),
        (url + "/?cmd=;cat%20/etc/passwd", None, "RCE via query string"),
        (url + "/", MALICIOUS_BODY.encode(), "SQLi no corpo (POST)"),
    ]

    for turl, tdata, label in tests:
        if stop_flag.is_set():
            dual_log("[*] Scan interrompido.")
            result["log"] = buffer
            return result
        dual_log(f"\n[*] Testando: {label} -> {turl}\n")
        try:
            s, h, b = fetch(turl, data=tdata, user_agent=user_agent,
                            headers={"Content-Type": "application/x-www-form-urlencoded"} if tdata else None)
        except Exception as e:
            dual_log(f"[!] Falha no teste {label}: {e}")
            continue
        if s is None:
            dual_log(f"[!] Falha: {b}")
            continue

        dual_log(f"    -> HTTP {s} (tamanho resposta: {len(b)})")

        changed = (s != status) or (abs(len(b) - len(body)) > 200) or (normalize_headers(h).get("server") != base_headers.get("server"))
        waf, score = match_fingerprint(s, h, b)
        if waf and score >= 3:
            dual_log(f"[+] WAF identificado: {waf} (score {score})")
            result["waf"] = waf
            result["details"].append(f"Gatilho: {label} -> HTTP {s}")
            result["log"] = buffer
            return result
        if changed and s in (403, 406, 429, 501):
            g = detect_generic_block(s, b)
            if g:
                dual_log(f"[~] Bloqueio genérico detectado ({', '.join(g)}) — WAF desconhecido")
                result["waf"] = "WAF genérico (desconhecido)"
                result["details"].append(f"Bloqueio HTTP {s} no teste '{label}': {', '.join(g)}")
                result["log"] = buffer
                return result
        dual_log("[-] Nenhum bloqueio observado neste teste")

    dual_log("[*] Scan concluído.")
    result["log"] = buffer
    return result

# ===================== GUI =====================
class WAFDetectorGUI:
    def __init__(self, root):
        self.root = root
        root.title("WAF Detector Pro v1.4")
        root.geometry("880x720")
        root.configure(bg="#0d1117")

        tk.Label(root, text="🛡 WAF Detector Pro v1.4", font=("Consolas", 18, "bold"),
                 bg="#0d1117", fg="#58a6ff").pack(pady=10)

        frm = tk.Frame(root, bg="#0d1117")
        frm.pack(fill="x", padx=15)

        tk.Label(frm, text="Alvo (URL ou domínio, um por linha):", bg="#0d1117",
                 fg="#c9d1d9", font=("Consolas", 10)).pack(anchor="w")

        self.targets = scrolledtext.ScrolledText(frm, height=5, bg="#161b22", fg="#c9d1d9",
                                                 insertbackground="#c9d1d9", font=("Consolas", 10))
        self.targets.pack(fill="x", pady=5)

        # ==================== USER-AGENTS ====================
        ua_frm = tk.Frame(frm, bg="#0d1117")
        ua_frm.pack(fill="x", pady=8)

        tk.Label(ua_frm, text="User-Agent (padrão ou personalizado):", bg="#0d1117",
                 fg="#c9d1d9", font=("Consolas", 10)).pack(anchor="w")

        self.user_agents_text = scrolledtext.ScrolledText(ua_frm, height=6, bg="#161b22", fg="#c9d1d9",
                                                         insertbackground="#c9d1d9", font=("Consolas", 10))
        self.user_agents_text.pack(fill="x", pady=4)

        btn_ua_frm = tk.Frame(ua_frm, bg="#0d1117")
        btn_ua_frm.pack(fill="x", pady=4)

        self.btn_import_ua = tk.Button(btn_ua_frm, text="📥 Importar User-Agents (txt)", command=self.import_user_agents,
                                       bg="#30363d", fg="#c9d1d9", font=("Consolas", 9))
        self.btn_import_ua.pack(side="left")

        self.lbl_ua_count = tk.Label(btn_ua_frm, text="0 User-Agents carregados", bg="#0d1117",
                                     fg="#8b949e", font=("Consolas", 9))
        self.lbl_ua_count.pack(side="left", padx=10)

        # ==================== CHECKBOXES ====================
        cb_frm = tk.Frame(ua_frm, bg="#0d1117")
        cb_frm.pack(fill="x", pady=6)

        self.use_custom_ua = tk.BooleanVar(value=False)
        # >>> MARCADO POR PADRÃO <<<
        self.use_encrypted_ua = tk.BooleanVar(value=True)

        cb_custom = tk.Checkbutton(cb_frm, text="Usar User-Agent personalizado (rotação automática do .txt)",
                                   variable=self.use_custom_ua,
                                   bg="#0d1117", fg="#c9d1d9", font=("Consolas", 9),
                                   activebackground="#0d1117", activeforeground="#c9d1d9",
                                   selectcolor="#161b22")
        cb_custom.pack(side="left", padx=10)

        # Checkbox "criptado" destacado em VERDE e já marcado
        cb_encrypted = tk.Checkbutton(cb_frm, text="Usar User-Agent criptado (dentro do script)",
                                      variable=self.use_encrypted_ua,
                                      bg="#0d1117", fg="#7ee787",
                                      font=("Consolas", 9, "bold"),
                                      activebackground="#0d1117", activeforeground="#7ee787",
                                      selectcolor="#161b22")
        cb_encrypted.pack(side="left", padx=10)

        # ==================== BOTOES ====================
        btns = tk.Frame(frm, bg="#0d1117")
        btns.pack(fill="x", pady=8)
        self.btn_start = tk.Button(btns, text="▶ Iniciar Scan", command=self.start_scan,
                                   bg="#238636", fg="white", font=("Consolas", 10, "bold"), relief="flat")
        self.btn_start.pack(side="left", padx=(0, 8))
        self.btn_stop = tk.Button(btns, text="■ Parar", command=self.stop_scan, state="disabled",
                                  bg="#b62324", fg="white", font=("Consolas", 10, "bold"), relief="flat")
        self.btn_stop.pack(side="left", padx=(0, 8))
        tk.Button(btns, text="📄 Exportar TXT", command=self.export_txt, bg="#30363d",
                  fg="#c9d1d9", font=("Consolas", 10), relief="flat").pack(side="left", padx=(0, 8))
        tk.Button(btns, text="🌐 Exportar HTML", command=self.export_html, bg="#1f6feb",
                  fg="white", font=("Consolas", 10, "bold"), relief="flat").pack(side="left")

        self.progress = ttk.Progressbar(frm, mode="determinate")
        self.progress.pack(fill="x", pady=5)

        tk.Label(root, text="Console:", bg="#0d1117", fg="#c9d1d9", font=("Consolas", 10)).pack(anchor="w", padx=15)
        self.logbox = scrolledtext.ScrolledText(root, height=12, bg="#010409", fg="#7ee787", font=("Consolas", 9))
        self.logbox.pack(fill="both", expand=True, padx=15, pady=(2, 5))

        tk.Label(root, text="Resultados:", bg="#0d1117", fg="#c9d1d9", font=("Consolas", 10)).pack(anchor="w", padx=15)
        self.results = scrolledtext.ScrolledText(root, height=8, bg="#010409", fg="#ff7b72", font=("Consolas", 10, "bold"))
        self.results.pack(fill="both", expand=True, padx=15, pady=(2, 10))

        self.q = queue.Queue()
        self.stop_flag = threading.Event()
        self.scan_results = []
        root.after(100, self.poll_queue)

    def log(self, msg):
        self.q.put(("log", msg))

    def poll_queue(self):
        try:
            while True:
                kind, msg = self.q.get_nowait()
                if kind == "log":
                    self.logbox.insert("end", msg + "\n")
                    self.logbox.see("end")
                elif kind == "result":
                    r = msg
                    line = (f"[{datetime.now().strftime('%H:%M:%S')}] {r['url']:<50}  ->  WAF: {r['waf']}\n")
                    r["line"] = line
                    self.results.insert("end", line)
                    self.results.see("end")
                elif kind == "done":
                    self.btn_start.config(state="normal")
                    self.btn_stop.config(state="disabled")
        except queue.Empty:
            pass
        self.root.after(100, self.poll_queue)

    def import_user_agents(self):
        path = filedialog.askopenfilename(filetypes=[("Text files", "*.txt"), ("All files", "*.*")])
        if not path:
            return
        try:
            with open(path, "r", encoding="utf-8") as f:
                lines = [line.strip() for line in f if line.strip()]
            if not lines:
                messagebox.showwarning("Aviso", "Arquivo vazio!")
                return
            self.user_agents_text.delete("1.0", "end")
            self.user_agents_text.insert("1.0", "\n".join(lines))
            self.lbl_ua_count.config(text=f"{len(lines)} User-Agents carregados", fg="#7ee787")
            messagebox.showinfo("Sucesso", f"{len(lines)} User-Agents carregados!\n"
                                           f"Modo automático: 1 User-Agent por alvo, em sequência (com ciclo).")
        except Exception as e:
            messagebox.showerror("Erro", str(e))

    def start_scan(self):
        raw = self.targets.get("1.0", "end").strip()
        targets = [t.strip() for t in raw.splitlines() if t.strip()]
        if not targets:
            messagebox.showwarning("Aviso", "Informe ao menos um alvo.")
            return

        # Obter User-Agents
        raw_ua = self.user_agents_text.get("1.0", "end").strip()
        ua_lines = [line.strip() for line in raw_ua.splitlines() if line.strip()]

        # ==================== ESCOLHA DO USER-AGENT ====================
        if self.use_encrypted_ua.get():
            # UA "criptado" (embutido no script) para todos os alvos
            user_agents = [USER_AGENT] * len(targets)
            ua_labels = ["criptado (embutido no script)"] * len(targets)
            self.log("[*] Usando User-Agent criptado (dentro do script)")
        else:
            if not ua_lines:
                messagebox.showwarning("Aviso",
                                       "Informe pelo menos um User-Agent!\n"
                                       "(ou marque 'Usar User-Agent criptado')")
                return
            # ===== ROTAÇÃO AUTOMÁTICA: 1 UA por alvo, em sequência =====
            # Se tiver mais alvos que UAs, recomeça a lista do início (ciclo)
            user_agents = [ua_lines[i % len(ua_lines)] for i in range(len(targets))]
            ua_labels = [f"lista .txt #{(i % len(ua_lines)) + 1}/{len(ua_lines)}" for i in range(len(targets))]
            self.log(f"[*] Rotação automática: {len(ua_lines)} User-Agents carregados "
                     f"para {len(targets)} alvo(s) — 1 UA por alvo, em sequência")

        self.btn_start.config(state="disabled")
        self.btn_stop.config(state="normal")
        self.stop_flag.clear()
        self.results.delete("1.0", "end")
        self.scan_results = []
        self.progress["value"] = 0

        def worker():
            total = len(targets)
            for i, t in enumerate(targets, 1):
                if self.stop_flag.is_set():
                    break
                self.log(f"\n===== Alvo {i}/{total} =====")

                # Pega o User-Agent deste alvo
                ua = user_agents[i-1]
                ua_label = ua_labels[i-1]
                # Mostra o User-Agent COMPLETO no console
                self.log(f"[*] User-Agent #{i} ({ua_label}): {ua}")

                r = scan_target(t, self.log, self.stop_flag, user_agent=ua, ua_label=ua_label)
                self.scan_results.append(r)
                self.q.put(("result", r))
                self.progress["value"] = (i / total) * 100
            self.q.put(("done", None))
            self.log("\n[*] Todos os scans finalizados\n\n")

        threading.Thread(target=worker, daemon=True).start()

    def stop_scan(self):
        self.stop_flag.set()
        self.log("[*] Interrompendo...")

    # ===================== EXPORTAÇÃO =====================
    def export_txt(self):
        if not self.scan_results:
            messagebox.showinfo("Info", "Nenhum resultado para exportar.")
            return
        path = filedialog.asksaveasfilename(defaultextension=".txt", filetypes=[("Texto", "*.txt")])
        if not path:
            return
        with open(path, "w", encoding="utf-8") as f:
            f.write("=" * 70 + "\n")
            f.write("WAF Detector Pro v1.4 - Relatório de Resultados\n")
            f.write(f"Gerado em: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}\n")
            f.write("=" * 70 + "\n\n")
            f.write("RESULTADOS (idênticos à aba 'Resultados' da GUI)\n")
            f.write("-" * 70 + "\n")
            for r in self.scan_results:
                f.write(r.get("line", f"{r['url']}  ->  WAF: {r['waf']}\n"))
            f.write("\n")
            for i, r in enumerate(self.scan_results, 1):
                f.write("=" * 70 + "\n")
                f.write(f"--- Alvo {i} ---\n")
                f.write(f"URL : {r['url']}\n")
                f.write(f"WAF : {r['waf']}\n")
                f.write(f"User-Agent ({r.get('ua_label', '')}): {r['user_agent']}\n")
                f.write("Detalhes:\n")
                for d in r["details"]:
                    f.write(f"  - {d}\n")
                f.write("\nCONSOLE (log completo do scan):\n")
                f.write("-" * 70 + "\n")
                for line in r.get("log", []):
                    f.write(line + "\n")
                f.write("\n")
        self.log(f"[+] Relatório TXT salvo em {path}")

    def export_html(self):
        if not self.scan_results:
            messagebox.showinfo("Info", "Nenhum resultado para exportar.")
            return

        import os
        import webbrowser

        stamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        default_name = f"relatorio_waf_{stamp}.html"
        path = filedialog.asksaveasfilename(defaultextension=".html", initialfile=default_name,
                                            filetypes=[("HTML", "*.html"), ("Todos os arquivos", "*.*")])
        if not path:
            return

        def esc(s):
            return (str(s).replace("&", "&amp;").replace("<", "&lt;")
                    .replace(">", "&gt;"))

        detected = sum(1 for r in self.scan_results if r["waf"] not in ("Nenhum detectado", "WAF genérico (desconhecido)"))
        generic = sum(1 for r in self.scan_results if r["waf"] == "WAF genérico (desconhecido)")
        clean = len(self.scan_results) - detected - generic

        cards = ""
        for i, r in enumerate(self.scan_results, 1):
            if "genérico" in r["waf"]:
                status_class = "warn"
                status_label = "GENÉRICO"
                status_icon = "⚠"
            elif r["waf"] == "Nenhum detectado":
                status_class = "ok"
                status_label = "LIMPO"
                status_icon = "✓"
            else:
                status_class = "bad"
                status_label = "DETECTADO"
                status_icon = "🛡"

            details = "".join(f"<li>{esc(d)}</li>" for d in r["details"]) or "<li class='muted'>Nenhum detalhe</li>"
            console = "".join(f"<div class='log-line'>{esc(l)}</div>" for l in r.get("log", []))

            cards += f"""
            <div class="card {status_class}" data-status="{status_class}" data-search="{esc(r['url']).lower()} {esc(r['waf']).lower()}">
                <div class="card-header">
                    <div class="card-header-left">
                        <span class="card-num">#{i:02d}</span>
                        <span class="card-icon">{status_icon}</span>
                        <div class="card-title">
                            <div class="card-url">{esc(r['url'])}</div>
                            <div class="card-waf">WAF: <b>{esc(r['waf'])}</b></div>
                            <div class="card-ua">User-Agent ({esc(r.get('ua_label', ''))}): <b>{esc(r['user_agent'])}</b></div>
                        </div>
                    </div>
                    <span class="badge {status_class}">{status_label}</span>
                </div>
                <div class="card-body">
                    <div class="section">
                        <div class="section-title">📋 Detalhes da Análise</div>
                        <ul class="details-list">{details}</ul>
                    </div>
                    <details class="section console-section">
                        <summary class="section-title clickable">💻 Console (Log Completo) — clique para expandir</summary>
                        <div class="console">{console}</div>
                    </details>
                </div>
            </div>"""

        html = f"""<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <title>WAF Detector Pro - Relatório {stamp}</title>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{ font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif; background: #0d1117; color: #c9d1d9; padding: 30px 40px; line-height: 1.5; }}
        .header {{ background: linear-gradient(135deg, #161b22 0%, #1f6feb22 100%); border: 1px solid #30363d; border-radius: 14px; padding: 28px 32px; margin-bottom: 25px; }}
        .header h1 {{ color: #58a6ff; font-size: 28px; margin-bottom: 8px; font-weight: 700; }}
        .header .sub {{ color: #8b949e; font-size: 13px; }}
        .stats {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin-bottom: 25px; }}
        .stat {{ background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 22px; text-align: center; }}
        .stat:hover {{ transform: translateY(-3px); border-color: #58a6ff; }}
        .stat .num {{ font-size: 34px; font-weight: 800; margin-bottom: 6px; }}
        .stat .lbl {{ font-size: 11px; color: #8b949e; text-transform: uppercase; letter-spacing: 1.2px; }}
        .num.total {{ color: #58a6ff; }} .num.bad {{ color: #ff7b72; }} .num.warn {{ color: #e3b341; }} .num.ok {{ color: #7ee787; }}
        .toolbar {{ display: flex; gap: 10px; margin-bottom: 20px; flex-wrap: wrap; align-items: center; background: #161b22; border: 1px solid #30363d; border-radius: 10px; padding: 12px 16px; }}
        .filter-btn {{ background: #21262d; color: #c9d1d9; border: 1px solid #30363d; padding: 8px 16px; border-radius: 6px; cursor: pointer; font-size: 12px; font-weight: 600; transition: all 0.15s; }}
        .filter-btn:hover {{ background: #30363d; }} .filter-btn.active {{ background: #1f6feb; border-color: #1f6feb; color: white; }}
        .search-box {{ flex: 1; min-width: 200px; background: #0d1117; border: 1px solid #30363d; color: #c9d1d9; padding: 8px 14px; border-radius: 6px; font-size: 13px; font-family: inherit; }}
        .cards-container {{ display: flex; flex-direction: column; gap: 15px; }}
        .card {{ background: #161b22; border: 1px solid #30363d; border-radius: 12px; overflow: hidden; transition: border-color 0.15s; }}
        .card:hover {{ border-color: #58a6ff; }}
        .card.ok {{ border-left: 5px solid #7ee787; }} .card.bad {{ border-left: 5px solid #ff7b72; }} .card.warn {{ border-left: 5px solid #e3b341; }}
        .card-header {{ display: flex; justify-content: space-between; align-items: center; padding: 16px 22px; background: #1c2128; border-bottom: 1px solid #30363d; }}
        .card-header-left {{ display: flex; align-items: center; gap: 14px; flex: 1; }}
        .card-num {{ background: #0d1117; color: #58a6ff; padding: 5px 11px; border-radius: 6px; font-family: 'Consolas', monospace; font-size: 12px; font-weight: 700; border: 1px solid #30363d; }}
        .card-icon {{ font-size: 22px; }}
        .card-title {{ flex: 1; min-width: 0; }}
        .card-url {{ color: #79c0ff; font-family: 'Consolas', monospace; font-size: 14px; font-weight: 600; word-break: break-all; margin-bottom: 3px; }}
        .card-waf {{ color: #8b949e; font-size: 12px; }}
        .card-waf b {{ color: #c9d1d9; }}
        .card-ua {{ color: #6e7681; font-size: 11px; margin-top: 3px; word-break: break-all; font-family: 'Consolas', monospace; }}
        .card-ua b {{ color: #8b949e; font-weight: 600; }}
        .badge {{ font-size: 10px; padding: 5px 12px; border-radius: 12px; font-weight: 700; letter-spacing: 0.8px; white-space: nowrap; }}
        .badge.bad {{ background: #ff7b7222; color: #ff7b72; border: 1px solid #ff7b72; }} .badge.warn {{ background: #e3b34122; color: #e3b341; border: 1px solid #e3b341; }} .badge.ok {{ background: #7ee78722; color: #7ee787; border: 1px solid #7ee787; }}
        .card-body {{ padding: 18px 22px; }}
        .section {{ margin-bottom: 14px; }}
        .section:last-child {{ margin-bottom: 0; }}
        .section-title {{ color: #58a6ff; font-size: 12px; text-transform: uppercase; letter-spacing: 1.2px; font-weight: 700; margin-bottom: 8px; }}
        .section-title.clickable {{ cursor: pointer; user-select: none; padding: 6px 0; }}
        .section-title.clickable:hover {{ color: #79c0ff; }}
        .details-list {{ list-style: none; padding-left: 4px; }}
        .details-list li {{ color: #c9d1d9; font-size: 13px; padding: 5px 0 5px 18px; position: relative; }}
        .details-list li::before {{ content: "▸"; position: absolute; left: 0; color: #58a6ff; }}
        .muted {{ color: #6e7681; font-style: italic; }}
        .console {{ background: #010409; border: 1px solid #30363d; border-radius: 6px; padding: 12px 14px; max-height: 300px; overflow-y: auto; font-family: 'Consolas', monospace; font-size: 11.5px; color: #7ee787; margin-top: 8px; }}
        .log-line {{ padding: 1px 0; white-space: pre-wrap; word-break: break-all; }}
        .console::-webkit-scrollbar {{ width: 8px; }}
        .console::-webkit-scrollbar-track {{ background: #161b22; }}
        .console::-webkit-scrollbar-thumb {{ background: #30363d; border-radius: 4px; }}
        details summary {{ list-style: none; }}
        details summary::-webkit-details-marker {{ display: none; }}
        details summary::before {{ content: "▶ "; color: #58a6ff; font-size: 10px; }}
        details[open] summary::before {{ content: "▼ "; }}
        .footer {{ text-align: center; color: #6e7681; font-size: 11px; margin-top: 30px; padding: 20px; border-top: 1px solid #30363d; }}
        .hidden {{ display: none !important; }}
        @media (max-width: 768px) {{ body {{ padding: 15px; }} .stats {{ grid-template-columns: repeat(2, 1fr); }} .card-header {{ flex-direction: column; align-items: flex-start; gap: 10px; }} }}
        @media print {{ body {{ background: white; color: black; }} .toolbar {{ display: none; }} details {{ open: true; }} }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡 WAF Detector Pro v1.4</h1>
        <div class="sub"> Relatório de Identificação de Web Application Firewall<br> Gerado em <b>{datetime.now().strftime('%d/%m/%Y às %H:%M:%S')}</b> — ID: <code>{stamp}</code> </div>
    </div>
    <div class="stats">
        <div class="stat" onclick="filterCards('all')"><div class="num total">{len(self.scan_results)}</div><div class="lbl">Total de Alvos</div></div>
        <div class="stat" onclick="filterCards('bad')"><div class="num bad">{detected}</div><div class="lbl">WAF Detectado</div></div>
        <div class="stat" onclick="filterCards('warn')"><div class="num warn">{generic}</div><div class="lbl">WAF Genérico</div></div>
        <div class="stat" onclick="filterCards('ok')"><div class="num ok">{clean}</div><div class="lbl">Sem Detecção</div></div>
    </div>
    <div class="toolbar">
        <button class="filter-btn active" onclick="filterCards('all', this)">📋 Todos</button>
        <button class="filter-btn" onclick="filterCards('bad', this)">🛡 Detectados</button>
        <button class="filter-btn" onclick="filterCards('warn', this)">⚠ Genéricos</button>
        <button class="filter-btn" onclick="filterCards('ok', this)">✓ Limpos</button>
        <input type="text" class="search-box" placeholder="🔍 Buscar por URL, WAF ou User-Agent..." oninput="searchCards(this.value)">
    </div>
    <div class="cards-container" id="cards">{cards}</div>
    <div class="footer"> WAF Detector Pro © {datetime.now().year} — Uso educacional / testes autorizados somente. </div>
    <script>
        function filterCards(status, btn) {{
            const cards = document.querySelectorAll('.card');
            cards.forEach(c => {{
                if (status === 'all' || c.dataset.status === status) c.classList.remove('hidden');
                else c.classList.add('hidden');
            }});
            if (btn) {{
                document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
                btn.classList.add('active');
            }}
        }}
        function searchCards(term) {{
            term = term.toLowerCase().trim();
            document.querySelectorAll('.card').forEach(c => {{
                if (!term || c.dataset.search.includes(term)) c.classList.remove('hidden');
                else c.classList.add('hidden');
            }});
        }}
    </script>
</body>
</html>"""

        try:
            with open(path, "w", encoding="utf-8") as f:
                f.write(html)
        except Exception as e:
            messagebox.showerror("Erro", f"Falha ao salvar: {e}")
            return

        self.log(f"[+] Relatório HTML salvo em {path}")
        if messagebox.askyesno("Abrir relatório", "Relatório salvo com sucesso!\nAbrir no navegador agora?"):
            try:
                webbrowser.open("file://" + os.path.abspath(path))
            except Exception as e:
                self.log(f"[!] Não foi possível abrir o navegador: {e}")

# ===================== EXECUÇÃO =====================
if __name__ == "__main__":
    root = tk.Tk()
    app = WAFDetectorGUI(root)
    root.mainloop()
